### ISSUE TITLE
icons request

### ISSUE THREAD

**Issue by denikris** [EliverLara/candy-icons#10]
- [x] audacious

- [x] audacious-qt

- [x] blueman-adapters

- [x] blueman-manager

- [x] brave-browser

- [x] catfish

- [x] dbx_preference

- [x] DockX

- [x] gparted

- [x] gpick

- [x] lightdm-gtk-greeter-settings

**Comment by EliverLara** [comment]
I have already added some of the icons, Could you provide some example of the remaining icons?

**Comment by denikris** [comment]
hi, this is rest of the icon when using xfce icon theme/hicolor, for dockbarx/dockx you can use same icon with symlink
![image3743](https://user-images.githubusercontent.com/16707606/63070591-fecce400-bf45-11e9-938a-b7b0aadbaf3f.png)
