### ISSUE TITLE
Issues with the new version

### ISSUE THREAD

**Issue by JarlavGrenland** [EliverLara/candy-icons#100]
After i updated to the new version some of the icons no longer change to the candy theme. 
![Skjermdump fra 2020-03-13 00-45-53](https://user-images.githubusercontent.com/52895632/76577038-4e679400-64c4-11ea-9ea5-2a57821845ea.png)
![Skjermdump fra 2020-03-13 00-45-59](https://user-images.githubusercontent.com/52895632/76577040-4f98c100-64c4-11ea-8aea-98c78cc996e2.png)
![Skjermdump fra 2020-03-13 00-47-56](https://user-images.githubusercontent.com/52895632/76577041-50c9ee00-64c4-11ea-9a01-40d17a71f47b.png)

**Comment by EliverLara** [comment]
Hi, that's a weird behavior, please make sure to completely remove the old version.

**Comment by JarlavGrenland** [comment]
> Hi, that's a weird behavior, please make sure to completely remove the old version.

So i did a fresh install of the Icon pack when i got that issue. Tried again with deleteing the current file and then installing it again seemed to a fixed the problem. Don't know what made the original install go whack. Software is weird sometimes hehehe - great icon pack ;)
