### ISSUE TITLE
[Icon Request] Jetbrains PyCharm tutanota

### ISSUE THREAD

**Issue by dmitriiweb** [EliverLara/candy-icons#102]
- [x] [Jetbrains PyCharm](https://www.jetbrains.com/pycharm/)

- [x] [tutanota email client](https://tutanota.com/blog/posts/desktop-clients/)

**Comment by sebastianpaweska** [comment]
https://github.com/EliverLara/candy-icons/issues/14
https://github.com/EliverLara/candy-icons/issues/50

**Comment by EliverLara** [comment]
Done!
