### ISSUE TITLE
[icon request] Zoom

### ISSUE THREAD

**Issue by OlivierBBB** [EliverLara/candy-icons#104]
Hi, thank you for your work! Could you add an icon for Zoom please?
Thanks

**Comment by PierreBergamin** [comment]
:pray: please!

**Comment by EliverLara** [comment]
Done!

**Comment by OlivierBBB** [comment]
Thank you very much : ) !

What are the steps to have candy-icons include the Zoom icon?

What I tried:
- I just restarted my pc and ran sudo apt update and sudo apt upgrade
- took a look at [this thread](https://github.com/EliverLara/candy-icons/issues/72) for slack and discord to try to set the zoom icon manually, but noticed that my /usr/share/icons/candy-icons/apps/scalable folder does not contain a Zoom icon.
