### ISSUE TITLE
[icon request] Few random programs 

### ISSUE THREAD

**Issue by JarlavGrenland** [EliverLara/candy-icons#106]
- [x] Foliate
![image](https://user-images.githubusercontent.com/52895632/77323625-dd22af00-6d15-11ea-9b69-25a4c5f8d0b4.png)
- [x] Girens
![image](https://user-images.githubusercontent.com/52895632/77323528-b2385b00-6d15-11ea-9012-c556d2138e43.png)
- [x] Yuna
![image](https://user-images.githubusercontent.com/52895632/77323561-c0867700-6d15-11ea-950f-14662a63b748.png)
- [x] Fragments
![image](https://user-images.githubusercontent.com/52895632/77324245-c16bd880-6d16-11ea-9906-d6d8f1aa4a95.png)

*" Continue the great work"*

**Comment by EliverLara** [comment]
Done!
