### ISSUE TITLE
icon fix for VS Code and icon request for Spotify

### ISSUE THREAD

**Issue by scottjanssen** [EliverLara/candy-icons#107]
The VS Code candy icon isn't working and I would like to request an icon for Spotify.

**Comment by JarlavGrenland** [comment]
there is a spotify icon already

**Comment by scottjanssen** [comment]
> there is a spotify icon already

Then it also doesn't work

**Comment by scottjanssen** [comment]
@JarlavGrenland The weird thing is that I can find the icon on my local drive for VS Code, but it simply won't translate to actual use.

**Comment by JarlavGrenland** [comment]
> 
> 
> @JarlavGrenland The weird thing is that I can find the icon on my local drive for VS Code, but it simply won't translate to actual use.

I guess it could be a bug or something else, strange. Don't have Spotify or VS code installed, but it hope it gets fixed for you.

**Comment by EliverLara** [comment]
Hi @scottjanssen , please make sure you have not installed those applications through `snap`, I think you could find the solution in #72 or #76 .

**Comment by scottjanssen** [comment]
@EliverLara @JarlavGrenland Thanks! I went ahead and manually changed the icons. It's too bad I had to do that but at least there is a fix!
