### ISSUE TITLE
Theme applied for folder icons, but not for apps

### ISSUE THREAD

**Issue by pittersnider** [EliverLara/candy-icons#108]
Hello Dear, I installed the theme and applied it via the GNOME Tweaks tool.  
The icons were changed (for folders) inside the "Files" app, but on Ubuntu's dock, no one updated, even for common apps (Chrome, Spotify, VSCode and so on). Can you assist me, please? This is the first time I am updating icons on Ubuntu/Gnome.

**Comment by EliverLara** [comment]
Hi, does this still persist?

**Comment by pittersnider** [comment]
Dear @EliverLara 

Yes, unfortunately, it does.

**Comment by EliverLara** [comment]
Does the theme not apply to any app icon or only to certain apps?

**Comment by pittersnider** [comment]
No one icon had changes, not even the most common (Chrome, VScode, Spotify, Slack, etc.)

**Comment by EliverLara** [comment]
Could you show me what's inside `candy-icons` folder, please?

**Comment by pittersnider** [comment]
Hi @EliverLara,

Somehow I fixed it by removing the older folder, downloading it again and applying it again.
Not sure what exactly has been fixed, but it looks to be working now.

Thank you,
Pitter.

**Comment by alireza-zamanian** [comment]
Hi @EliverLara 

I have the same issue here. and re-downloading did not solve it. the icons for folders have changed, but apps like Telegram Desktop, Pycharm, Spotify, etc have not

Here is a screenshot from inside of the folder, as asked @pittersnider 

![Screenshot from 2020-04-12 21-22-44](https://user-images.githubusercontent.com/41769625/79077713-c6afb800-7d03-11ea-8338-bb8f20b25b0a.png)

**Comment by alireza-zamanian** [comment]
> Hi @EliverLara
> 
> I have the same issue here. and re-downloading did not solve it. the icons for folders have changed, but apps like Telegram Desktop, Pycharm, Spotify, etc have not
> 
> Here is a screenshot from inside of the folder, as asked @pittersnider
> 
> ![Screenshot from 2020-04-12 21-22-44](https://user-images.githubusercontent.com/41769625/79077713-c6afb800-7d03-11ea-8338-bb8f20b25b0a.png)

I think only the apps downloaded from software center (in the snap folder) are the problem. I installed 'Typora' using `apt install` and the icon is applied. Those apps that has not changed has been installed from the software center
