### ISSUE TITLE
folder icons in thunar look different from one in preview

### ISSUE THREAD

**Issue by denikris** [EliverLara/candy-icons#11]
xubuntu 18.04.2
xfce 4.12.x
thunar 1.6.x
![Screenshot_2019-07-28_13-18-09](https://user-images.githubusercontent.com/16707606/62003042-79ba9000-b13a-11e9-8916-a4cbdec17a50.png)
there is stroke line color (lime green i think) that kinda odd to mix with fill color

**Comment by EliverLara** [comment]
Thanks for reporting! tha's fixed now
