### ISSUE TITLE
Not completley working

### ISSUE THREAD

**Issue by AndrGutierrez** [EliverLara/candy-icons#110]
I have installed the icons, but some of them doesn't apply :( like vs code, whatsapp desk, even the calculator

pd: I love these icons, you are a completley madlad :100: 
pd 2: sorry if my english is not the best :b

**Comment by EliverLara** [comment]
Hi @AndrGutierrez , please make sure you have not installed those applications through `snap`, I think you could find the solution in #72 , #76 or #79.
