### ISSUE TITLE
[Icon Request] Slack, VSCode-Insiders, Teams-Insiders, and Insomnia

### ISSUE THREAD

**Issue by pittersnider** [EliverLara/candy-icons#111]
Dear team,

I want to ask you to work on the app icons:

- [x] - "Microsoft Teams - Insiders"
- [x] - "Visual Studio Code - Insiders"
- [x] - "Insomnia" (Rest Client)
- [x] - "Slack" (Messaging App)

Thanks for the attention,
Pitter.

**Comment by EliverLara** [comment]
Done!
