### ISSUE TITLE
Icons not applied to Snap (software center) Apps

### ISSUE THREAD

**Issue by alireza-zamanian** [EliverLara/candy-icons#115]
I commented on the issue #108 because I had the same problem and it is not solved yet. I thing the problem is with the apps that are installed via snap, or the software center, such as _bitwarden_, _Telegram_, _Spotify_, _Pycharm_.

But when I install apps via `apt install`, Then it is OK, such as _Typora_, or _Zotero_. For the files and folder as well, everything works like a charm.

As you requested in the mentioned issue, I took a screenshot of the contents inside the `candy-icons` folder
![79077713-c6afb800-7d03-11ea-8338-bb8f20b25b0a](https://user-images.githubusercontent.com/41769625/79206467-ad138b00-7e3f-11ea-9a86-7280cbec2271.png)

**Comment by EliverLara** [comment]
Applications installed via snap  have hardcoded path to icons, so you must manually change that, please take a look to #72 , #76 or #79.

**Comment by alireza-zamanian** [comment]
Thank you very much. it fixed the issue. Just a quick comment. I couldn't find the `.desktop` files in the directory mentioned in the other issues which was `/usr/share/applications/`. rather found it in: `/var/lib/snapd/desktop/applications`

**Comment by Diogenes06** [comment]
@alireza-zamanian Thanks for the help man I wes having the same issue and couldn't find a way to solve it. Thanks again
