### ISSUE TITLE
Request icons

### ISSUE THREAD

**Issue by Deusgone** [EliverLara/candy-icons#12]
- [x] Spotify

- [x] Simplenote

- [x] Stacer

- [ ] Show Desktop

- [ ] Shutdown, Logoff, etc

**Comment by EliverLara** [comment]
I have already added some of the icons, could you provide some example of the remaining icons?

**Comment by Deusgone** [comment]
Thanks, please incluse "Lutris Icon" and "show desktop on Plank"

**Comment by Deusgone** [comment]
Thank for everything, please this icons:

- Pycharm Community Edition
- Lutris
- Show Desktop (Plank Icon)
