### ISSUE TITLE
[Icon Request] Deluge Freetube Cozy-audiobooks Ferdi Qalculate! ClamTK KMyMoney Plex-Media-Player Nut-Monitor

### ISSUE THREAD

**Issue by Moitaeel** [EliverLara/candy-icons#121]
Hello mate, first I want to congratulate you on the icon pack, it's very pretty and concise.

I also want to make an icon request for these programs (if possible):

- [x] deluge
`deluge`
https://github.com/deluge-torrent/deluge
![](https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Deluge-Logo.svg/1024px-Deluge-Logo.svg.png)

- [x] Freetube
`freetube-bin`
https://github.com/FreeTubeApp/FreeTube
![](https://steemitimages.com/DQmfF37wuRozsaDYizjyY6PsNKWxU3TN2X9FbR45UT6PwjH/main.png)

- [x] Cozy
`com.github.geigi.cozy`
https://github.com/geigi/cozy
![](https://raw.githubusercontent.com/geigi/cozy/e4ddbfce0568ae5a4b66b45e07c064d566bd5d2a/data/icons/hicolor/128x128/apps/com.github.geigi.cozy.svg)

- [x] Ferdi
`ferdi`
https://github.com/getferdi/ferdi
![](https://raw.githubusercontent.com/getferdi/ferdi/develop/build-helpers/images/icon.png)

- [x] Qalculate!
`qalculate-gtk`
https://github.com/Qalculate/qalculate-gtk
![](https://raw.githubusercontent.com/Qalculate/qalculate-gtk/72c4de0b995c09ee1bd4c34aff6da6dd9883f9c0/data/icons/scalable/qalculate-sizes.svg)

- [x] ClamTK
`clamtk`
https://github.com/dave-theunsub/clamtk
![](https://raw.githubusercontent.com/dave-theunsub/clamtk/master/images/clamtk.png)

- [x] KMyMoney
`kmymoney`
https://github.com/KDE/kmymoney
![](https://raw.githubusercontent.com/KDE/kmymoney/master/kmymoney/icons/kmymoney/apps/128-apps-kmymoney.png)

- [x] Plex-Media-Player
`plexmediaplayer`
https://github.com/plexinc/plex-media-player
![](https://raw.githubusercontent.com/plexinc/plex-media-player/master/resources/images/icon.png)

- [x] Nut-Monitor
`nut-monitor`
https://github.com/networkupstools/nut
![](https://raw.githubusercontent.com/networkupstools/nut/master/scripts/python/app/icons/256x256/nut-monitor.png)

Thanks mate

**Comment by EliverLara** [comment]
Done!
