### ISSUE TITLE
[Icon Request] Quod Libet & Pencil

### ISSUE THREAD

**Issue by webdevsuperfast** [EliverLara/candy-icons#128]
@EliverLara elegant set of icons, kindly add the following:

- [ ] [Quod Libet](https://quodlibet.readthedocs.io/en/latest/)
- [ ] [Pencil](https://pencil.evolus.vn/)

Thank you :)

**Comment by dannn-o** [comment]
+1 vote for Quod Libet:
![Screenshot from 2020-05-13 11-59-13](https://user-images.githubusercontent.com/17674969/81836351-54eca900-9511-11ea-8464-2925bfef2853.png)

**Comment by EliverLara** [comment]
Done!
