### ISSUE TITLE
Icons request

### ISSUE THREAD

**Issue by backspac** [EliverLara/candy-icons#13]
Hey! I love your icons! Great work there! Here are some I'd like to see:

- [x] Cantata

- [x] mpv

- [x] Mumble

- [x] Signal

- [x] digiKam

- [x] Krita

**Comment by EliverLara** [comment]
I have already added some of the icons, could you provide some example of the remaining icons?

**Comment by backspac** [comment]
Sure. Here it is:

![signal-desktop](https://user-images.githubusercontent.com/8981640/63050293-0905c880-bedb-11e9-90f8-9e9823846c0d.png)

The other ones already look amazing!
