### ISSUE TITLE
[Icon Request]

### ISSUE THREAD

**Issue by suku-23** [EliverLara/candy-icons#130]
Amazing work! Kindly consider makeing 'Visual Studio Code' and 'Discord' icons when you get time.
Thanks
-

**Comment by EliverLara** [comment]
Hi, there are already icons for those apps, please, make sure you haven't installed them via snap becasuse applications installed via snap have hardcoded path to icons, so you must manually change that, please take a look to #72 , #76 or #79.

**Comment by suku-23** [comment]
Thanks, that resolved the issue. 
Again kudos to your good work.
--
