### ISSUE TITLE
[Icon Request] Remmina

### ISSUE THREAD

**Issue by dannn-o** [EliverLara/candy-icons#132]
Love the icon set.  Opening this to request an icon for Remmina be added.
[https://remmina.org/](url)
![Screenshot from 2020-05-13 12-04-09](https://user-images.githubusercontent.com/17674969/81836746-e5c38480-9511-11ea-8ed8-600718e11b8d.png)

I'm fairly competent with GIMP and Inkscape...would be glad to help you with icon conversions if
it's possible to give me a bit of guidance.  Thanks again.

**Comment by EliverLara** [comment]
Done!
