### ISSUE TITLE
[Icon Request] Spotify, Riot, VSCode

### ISSUE THREAD

**Issue by IngwiePhoenix** [EliverLara/candy-icons#133]
Hey there!

I found this icon theme through Reddit and paired it with [NeonKnights](https://www.gnome-look.org/p/1301852/) and it looks plain amazing! However, seing three of my most used apps not themed is a little annoying :)

Therefore, I would love to make an icon request for Spotify, Riot and Visual Studio Code!

Thank you very much for those amazing looking icons - they are so stunning!

Kind regards and have a great day!

**Comment by EliverLara** [comment]
I've added the riot icon, vscode and spotify already have an icon, please, make sure you haven't installed them via snap becasuse applications installed via snap have hardcoded path to icons, so you must manually change that, please take a look to #72 , #76 or #79.
