### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by Auraculum** [EliverLara/candy-icons#135]
I would like to request that icons be made for the following apps:
- qBitTorrent,
- Notepadqq or Notepad++,

Thank you. :)

**Comment by dannn-o** [comment]
I use qBittorrent and there is an icon for it already:

![qBittorrent](https://user-images.githubusercontent.com/17674969/82232164-3e24c880-98fc-11ea-926e-b6e08e8c1f2b.png)

**Comment by Auraculum** [comment]
Terribly sorry, didn't notice it. I'm converting hem to the .ico format to use it in Windows 10, so I might've missed that one. :)

**Comment by Auraculum** [comment]
Still could very much use an icon for either Notepad++ or Notepadqq, or just a general "notepadish" icon.

**Comment by dannn-o** [comment]
The author(s) of Candy-icons seem responsive, but if you're looking for an existing icon you can use, maybe either Xedit:

![xedit](https://user-images.githubusercontent.com/17674969/82332072-f1e88f80-99b2-11ea-8ec9-cdc4552fc5d7.png)

or Gnote:
![accessories-notes](https://user-images.githubusercontent.com/17674969/82332247-265c4b80-99b3-11ea-8219-0ec6b86c5a1d.png)

I don't think these apps would conflict with anything in Windows 10.
