### ISSUE TITLE
[Icon Request] Celluloid

### ISSUE THREAD

**Issue by dannn-o** [EliverLara/candy-icons#137]
Thanks for your quick turnaround on the other recent requests!

Linux Mint has switched to Celluloid for the default multimedia player, if you can add an icon for that:
[https://github.com/celluloid-player/celluloid](url)

![Celluloid](https://user-images.githubusercontent.com/17674969/82232443-a2e02300-98fc-11ea-9027-2d34f7c14302.png)

**Comment by EliverLara** [comment]
Done!

**Comment by dannn-o** [comment]
Thanks again - love the icon set!  How long before an update shows in the Master branch?  Looks like the last commit was 11 days ago.
