### ISSUE TITLE
Icon Request - Azure Data Studio

### ISSUE THREAD

**Issue by LarnuUK** [EliverLara/candy-icons#139]
We have an icon for VSCode, it would be great to have one for [ADS](https://docs.microsoft.com/en-us/sql/azure-data-studio/download-azure-data-studio?view=sql-server-ver15) too. This is their [current logo](https://pbs.twimg.com/profile_images/925790808103456769/X6m3TwZo.jpg).

Thanks!

**Comment by EliverLara** [comment]
Done!
