### ISSUE TITLE
Different Icons showing up in Tray

### ISSUE THREAD

**Issue by ksdfg** [EliverLara/candy-icons#145]
I'm using arch linux with cinnamon

![image](https://user-images.githubusercontent.com/43273771/84270257-06e6b780-ab48-11ea-8563-78f4d12ec736.png)

As you can see, the tray icons for some applications (e.g. Zoom, Teams) is different than the one you see when you open the application. Since some apps like Telegram and qBittorrent have the same icon, this is disorienting.

If it cannot be fixed in repo, then please tell me how I can fix it locally.

**Comment by EliverLara** [comment]
Hi, I'm sorry for the very late response, Are you still facing this issue?

**Comment by ksdfg** [comment]
Yeah, I am for teams.... have uninstalled zoom since then, so not sure about that.

Also no need to apologize for late response, I'm pretty sure you have your hands full :)

**Comment by EliverLara** [comment]
Thanks for the quick response, a common cause of the issue could be that the application has been installed via snap, Could you verify if it is not your case, please?

**Comment by ksdfg** [comment]
I'm on arch linux, I installed teams via `yay`

**Comment by EliverLara** [comment]
Could you provide the next entries, please, 

- **App Name:**
- **Icon Name:**

NOTE:
You'll find most of necessary entries for the icon request in a app's desktop-file, usually placed in `/usr/share/applications/folder` (Ex. `/usr/share/applications/firefox.desktop`).

**Comment by ksdfg** [comment]
![image](https://user-images.githubusercontent.com/43273771/97620186-32126a80-1a47-11eb-9618-1aa7463ede11.png)

- Version=1.0
- Type=Application
- Name=Microsoft Teams - Preview
- Comment=Microsoft Teams for Linux is your chat-centered workspace in Office 365.
- Exec=teams %U
- Icon=teams
- Terminal=false
- StartupNotify=true
- StartupWMClass=Microsoft Teams - Preview
- Categories=Network;
- MimeType=x-scheme-handler/msteams;
- X-KDE-Protocols=teams
- Actions=QuitTeams;
- X-GNOME-UsesNotifications=true;

Sorry for the spam, but I wasn't sure what you needed :sweat_smile:

**Comment by EliverLara** [comment]
This is odd because there is already an icon matching that `icon name`

**Comment by ksdfg** [comment]
> This is odd because there is already an icon matching that `icon name`

I'm not sure, maybe there's another separate icon for the tray? I've tried finding it, but I can't.......

**Comment by ksdfg** [comment]
I just managed to fix the Icon for teams in the tray! Had to go and replace `/usr/share/teams/resources/assets/Presence-NoActivity-Systray16x16@2x` manually. Converted the svg you'd given into png and replaced the file, it's working fine now!
