### ISSUE TITLE
[icons request] 

### ISSUE THREAD

**Issue by MarioMohr** [EliverLara/candy-icons#149]
Your icons and themes rock ! Thanks for that.

I would be pleased when you add the following icons  ...

- [x] * Virt-Manager
- [x] * VirtualBox
- [x] * VMware
- [x] * qemu !!!
- [x] * Lutris
- [x] * PlayOnLinux
- [ ] * MS Windows
- [x] * Gentoo

In the Gnome Favorite Bar (Dock) there is an button to show applications (hamburger) and this its still default grey.
Not sure this is the right place to make a request like this, maybe I should create a request for your sweet-dark theme too ?

**Comment by autopr3z** [comment]
Didn't want to open another issue, but a gentoo icon would be great!
