### ISSUE TITLE
Visual Studio Code icon feels like Visual Studio Icon

### ISSUE THREAD

**Issue by LarnuUK** [EliverLara/candy-icons#150]
This is more of an observation, but the icon used for VSCode (at least to me) feels more like an alternative for Visual Studio's icon. This is the current VS Code Icon in the Icon set:
![image](https://user-images.githubusercontent.com/20837086/84894420-b5cf4a00-b098-11ea-91a0-3be1b8717522.png)
The key note is that it's purple, which is Visual Studio's colour (not VS Codes). Visual Studio's icon has changed a lot over the years, but they're all purple in colour:
![image](https://user-images.githubusercontent.com/20837086/84894605-f929b880-b098-11ea-9d06-ce8b622d6a85.png)

Visual Studio Code (VSCode)'s icon, however, is blue, not purple:
![image](https://user-images.githubusercontent.com/20837086/84895733-b072ff00-b09a-11ea-9209-0cbd38ea6434.png)

VSCode insiders icon, in the icon pack, actually feels more like the correct colour for the VSCode application:
![image](https://user-images.githubusercontent.com/20837086/84895802-c7b1ec80-b09a-11ea-9a2f-3b751521f829.png)

But the actual VSCode Insiders application is green, not blue, and has little cut outs:
![image](https://user-images.githubusercontent.com/20837086/84895586-6f7aea80-b09a-11ea-85ec-c7ce6ec42fb1.png)

Like I said though, these are more observations, but sometimes does throw me off a bit when swapping from a Windows Environment to my Linux Environment.

**Comment by LarnuUK** [comment]
Also, the Visual Studio Code - Insiders Icon doesn't appear to be working, even after a restart log off/on:
![image](https://user-images.githubusercontent.com/20837086/84926902-f7291f00-b0c3-11ea-82f0-34a645d70f0e.png)

**Comment by LarnuUK** [comment]
Fixed the icon not working by adding a further symlink: `com.visualstudio.code.insiders.svg`. 

I also, made personal adjustments to the icons on my PC. I switch the VS Code Insiders icon to the VS Code icon, and then editted the icon the be the below for the Insiders build (I am not a graphics person, I suspect my line cuts are awful, but they work when the icon is small :) )
![image](https://user-images.githubusercontent.com/20837086/84929674-0e6a0b80-b0c8-11ea-8571-dd0dbb65f1c1.png)

**Comment by EliverLara** [comment]
I've updated the colors to better match the originals.
