### ISSUE TITLE
[Icon request] generic twitter icon

### ISSUE THREAD

**Issue by myyc** [EliverLara/candy-icons#151]
Hey. These icons are great and it looks like you already have a huge backlog of requests. Not sure if this is exotic, but maybe it'd be useful to have a generic "twitter" icon, just like the "messenger" and "whatsapp" icons, to be recycled for this or that client (e.g. cawbird ...)

**Comment by EliverLara** [comment]
Done!

**Comment by ThisNekoGuy** [comment]
Can this be done for Cawbird in particular?
Cawbird's logo his nauseatingly bad... :sweat_smile:
