### ISSUE TITLE
[Icon Request] MongoDB Compass

### ISSUE THREAD

**Issue by rhill13** [EliverLara/candy-icons#153]
Awesome icons and themes! Love them!
If you get a chance, could you perhaps look at making a mongoDB icon?

- [mongoDB Logo](https://www.mongodb.com/brand-resources)

- ![mongodb-screenshot](https://user-images.githubusercontent.com/38714415/85330027-3b883680-b499-11ea-9f93-7179c3b8e659.png)

Thanks!

**Comment by EliverLara** [comment]
Done!
