### ISSUE TITLE
[Icon Request] Two chat programs

### ISSUE THREAD

**Issue by JarlavGrenland** [EliverLara/candy-icons#156]
- [x] [Dino](https://dino.im/)
![26004739](https://user-images.githubusercontent.com/52895632/86419522-f2b75580-bcc2-11ea-9497-10aae0773079.png)
- [x] [GTKCord](https://github.com/diamondburned/gtkcord3)
![gtkcord](https://user-images.githubusercontent.com/52895632/86419795-e7185e80-bcc3-11ea-9877-97ec94a3d8c8.png)

**Comment by EliverLara** [comment]
Done!

**Comment by Greylinux** [comment]
@EliverLara 
I think the Dino one is no longer working it shows as the standard icon again , should open a new issue ?
