### ISSUE TITLE
[Icon Request] (Fedora Cinnamon Version) Linux Icons

### ISSUE THREAD

**Issue by yusi22** [EliverLara/candy-icons#158]
Most icons on Fedora are there, except: Fedy, Shutter (https://shutter-project.org/), Lutris, Dnfdragora, DnfDragora-Updater, Plex Media Player, Mixxx, SELinux Troubleshooter, redshift color management (hard to find on google so here's the link: http://jonls.dk/redshift/#:~:text=Redshift%20adjusts%20the%20color%20temperature%20according%20to%20the%20position%20of%20the%20sun.&text=This%20is%20typically%20a%20low,6500K%20(default%20is%205500K).), Pidgin Internet Messager.
Their are some more missing icons but they are not apps, more like recent places on the cinnamon menu and computer on the desktop. Otherwise I love this icon theme, basically all the apps on my pc have the correct icons!! You guys did an amazing job. Apps that are hard to find on google are linked.

**Comment by yusi22** [comment]
Also, Google Web Designer's icon would be a nice touch.

**Comment by yusi22** [comment]
Example of missing "computer" icon and "recent places":
![Selection_034](https://user-images.githubusercontent.com/67838383/86518349-388e2e00-be29-11ea-8ab5-42b39aedb88e.png)
![Desktop_038](https://user-images.githubusercontent.com/67838383/86518388-ab97a480-be29-11ea-8867-534c2dee421c.png)

**Comment by yusi22** [comment]
Also, CKB-NEXT's (https://github.com/ckb-next/ckb-next) icon is missing too.

**Comment by yusi22** [comment]
Fedy:
![plank_040](https://user-images.githubusercontent.com/67838383/86538181-4c4e9880-beec-11ea-912b-b2043fbb88df.png)
Shutter:
![Selection_041](https://user-images.githubusercontent.com/67838383/86538188-540e3d00-beec-11ea-96f9-24a6529b28e7.png)
Lutris:
![Selection_042](https://user-images.githubusercontent.com/67838383/86538194-5a9cb480-beec-11ea-8f25-df2505f218c9.png)
DNFDragora:
![Selection_043](https://user-images.githubusercontent.com/67838383/86538198-5ff9ff00-beec-11ea-93fc-fcfa2bbf1340.png)

**Comment by Hasshu** [comment]
> DNFDragora

Incidentally, dnfdragora has a different icon now: https://github.com/manatools/dnfdragora#readme

**Comment by yusi22** [comment]
That's odd, on my fully-updated Fedora system it still has the old icon?? I guess Fedora must be using an older version of the package?

**Comment by yusi22** [comment]
Looking at [this](https://www.reddit.com/r/Fedora/comments/7p0ook/how_did_dnfdragora_get_installed_on_my_machine/) points to dnf-dragora also being included in the kde-desktop group, kde must have the newer version maybe?

**Comment by Hasshu** [comment]
> That's odd, on my fully-updated Fedora system it still has the old icon?? I guess Fedora must be using an older version of the package?

Indeed, Fedora still has the old (and buggy) v2.0.0 in the repos, while the latest is v2.0.4.

> Looking at this points to dnf-dragora also being included in the kde-desktop group, kde must have the newer version maybe?

They use the same repositories, so no. The newer versions just haven't been packaged yet, for whatever reason.
