### ISSUE TITLE
[Icon Request] Firefox Nightly

### ISSUE THREAD

**Issue by romhacks** [EliverLara/candy-icons#159]
Firefox nightly is the most bleeding edge (and unstable) version of Firefox. It's icon is a re-colored version of the normal icon, with deep blues and purples. [Here is the current icon from Mozilla.](https://external-preview.redd.it/t-S1-9YB32zPWpLqD8vKIWxZztdfJU4Th7BC0thvt3E.png?auto=webp&s=111df9d1901b55516567e2252b411b2f4c74a76f)

**Comment by EliverLara** [comment]
Done!
