### ISSUE TITLE
Icon requests

### ISSUE THREAD

**Issue by PKGaspi** [EliverLara/candy-icons#16]
Please, add the following icons:

- [x] Retroarch
- [x] WhatsApp
- [x] Games folder (and more folder types if possible)
- [x] Minecraft
- [ ] File icons (.pdf, .java, .py, .tex, .html, .md, etc.)
- [x] Krita
- [x] KDE icons (applications, settings menu icons, etc.)
- [x] OBS
- [ ] f.lux

Please, revise the following icons:

- Firefox (sharp thin edges)
- Lollypop (middle lines scale wrong when the icon is small)

Thank you very much, I really love the icon pack so far.

**Comment by fla15** [comment]
![Screenshot from 2019-10-03 09-42-23](https://user-images.githubusercontent.com/30726939/66103571-1aa64b00-e5c3-11e9-944f-6e519e473583.png)
![Screenshot from 2019-10-03 09-42-18](https://user-images.githubusercontent.com/30726939/66103591-24c84980-e5c3-11e9-8250-c91e617fe14f.png)
also LibreOffice files icon it's too old

**Comment by EliverLara** [comment]
I have already added some of the icons, Could you provide some example of the remaining icons?

**Comment by creepertron95** [comment]
- Minecraft:
![minecraft](https://user-images.githubusercontent.com/53346722/76258920-85b71600-6222-11ea-8409-579b599235db.png)

- f.lux:
![flux](https://user-images.githubusercontent.com/53346722/76258946-8fd91480-6222-11ea-8ad7-d2671e649b7d.png)
