### ISSUE TITLE
[Icon Request] Request for some app icons.

### ISSUE THREAD

**Issue by digvijay-r** [EliverLara/candy-icons#163]
Here are the list of some icons which are not present in this:

- [x] - Visual Studio Code
- [x] - Chromium Browser
- [x] - Telegram
- [x] - Robo 3T
- [x] - Postman
- [x] - Spotify
- [x] - Cliq
- [x] - Skype
- [x] - Beyond Compare
- [x] - Redis Desktop Manager

**Comment by digvijay-r** [comment]
I think i have issue while applying the icon theme. The icon theme isn't applicable for the snap apps. How can I fix this.

**Comment by dtsyosh** [comment]
I'm having this same problem .. Someone?
