### ISSUE TITLE
[Icon Request] thinkorswim

### ISSUE THREAD

**Issue by Rfvgyhn** [EliverLara/candy-icons#168]
App: https://www.tdameritrade.com/tools-and-platforms/thinkorswim/desktop.page
Logo + Name: https://auth.tdameritrade.com/ux/c4079/tda_trader_x/logos/liveTrading.svg
Sample Desktop File:
```
[Desktop Entry]
Type=Application
Name=thinkorswim
Exec="/home/user/.local/share/thinkorswim/thinkorswim"
Icon=thinkorswim
```

**Comment by EliverLara** [comment]
Done!
