### ISSUE TITLE
[Icon Request] Terraria

### ISSUE THREAD

**Issue by billyb2** [EliverLara/candy-icons#175]
Hi,
After looking through your Github repo to triple check that you haven't, I was wondering if you could make an icon for Terraria?

**Comment by EliverLara** [comment]
Hi, Could you provide some example(maybe default icon) of the requested icon?

**Comment by Paragoumba** [comment]
![Terraria](https://user-images.githubusercontent.com/22895992/97485918-0c0f9c00-195b-11eb-879a-32af59fc4f77.png)
Only the tree-part of this icon is used for the executable
