### ISSUE TITLE
Steam icon broken

### ISSUE THREAD

**Issue by Paragoumba** [EliverLara/candy-icons#179]
The two thin circles should be thicker
![image](https://user-images.githubusercontent.com/22895992/95597302-baa47900-0a4e-11eb-953c-f04585baef79.png)

**Comment by Bodhi-Teraguchi** [comment]
I do not have this problem.  Have you tried reinstalling the pack?

**Comment by Paragoumba** [comment]
I updated and it is still happening

**Comment by EliverLara** [comment]
Fixed, thanks for reporting!
