### ISSUE TITLE
Contribute

### ISSUE THREAD

**Issue by ZVak18** [EliverLara/candy-icons#18]
Hello.
I'd like to contribute 2 icons to your set.
I've updated the Firefox icon to match one of their more modern styles.
[Firefox](https://github.com/ZVak18/candy-icons/blob/master/apps/scalable/firefox.svg)
I've also added an icon for the LightDM greeter settings.
[LightDM](https://github.com/ZVak18/candy-icons/blob/master/apps/scalable/lightdm-gtk-greeter-settings.svg)

Hope they fit with your style and standards.
Thanks so much.

**Comment by EliverLara** [comment]
Thanks for contributing! I will review them, it would be helpful if you could open a pull request to propose these changes

**Comment by ZVak18** [comment]
I actually did that originally, but I was abit worried about it showing the other changes I've made that I don't want to pull request on. Are you able to select only those changes that you want?
Sorry quite new to doing pull requests.

**Comment by EliverLara** [comment]
The ideal point is to do the pull request when you have your icon ready in your repo, I mean, just add the icon you want in your repo and then do the pull request

**Comment by ZVak18** [comment]
Sounds good. Pull request has been created. Please let me know if you need anything additional.

**Comment by nandumoura** [comment]
hou to install a theme or icons in my system
