### ISSUE TITLE
Hacktoberfest tag

### ISSUE THREAD

**Issue by vanntile** [EliverLara/candy-icons#185]
Hello, I have made three icons that I am currently using, in the style of this amazing theme and created PRs to them #182 #183 #184 

I would appreciate if you could add the `hacktoberfest` topic on your repository or, if you accept these three new additions, to tag the PRs with `hacktoberfest-accepted`.

Even if you won't, keep up the good work, this is a delicate neon theme.

**Comment by EliverLara** [comment]
Done!
