### ISSUE TITLE
[Icon Request] Scene Builder

### ISSUE THREAD

**Issue by jackpeters667** [EliverLara/candy-icons#186]
Requesting an icon for GluonHQ's Scene Builder

**Comment by EliverLara** [comment]
Hi, Could you provide an example of the requested icon, please?

**Comment by Paragoumba** [comment]
![SceneBuilderLogo](https://user-images.githubusercontent.com/22895992/97350961-6f34fc00-1891-11eb-94b3-a1613097159f.png)
