### ISSUE TITLE
[Icon Request] Microsoft Edge (Chromium)

### ISSUE THREAD

**Issue by jackpeters667** [EliverLara/candy-icons#187]
So the new Microsoft Edge is available on the linux dev channel now. I figure it's about time until more people start using it.

**Comment by sagarthomas** [comment]
Not sure if I'm just blind but I don't see the Microsoft Edge icon listed in the repo. I cloned the latest version of the repo and installed the icons but Edge still shows up as its normal icon. I'm using the Edge dev channel release since the official stable version isn't released yet.

**Comment by IncognitaDev** [comment]
> Not sure if I'm just blind but I don't see the Microsoft Edge icon listed in the repo. I cloned the latest version of the repo and installed the icons but Edge still shows up as its normal icon. I'm using the Edge dev channel release since the official stable version isn't released yet.

Have a pull request about this icon, download the icon from de fork, add to candy-icons folder and will work
