### ISSUE TITLE
[Icon Request] Rclone Browser & pamac-aur

### ISSUE THREAD

**Issue by eyuphuro** [EliverLara/candy-icons#188]

**Comment by EliverLara** [comment]
Hi,  Could you provide some example(maybe default icon) of the requested icons?

**Comment by eyuphuro** [comment]
![image](https://user-images.githubusercontent.com/13303659/97796109-c4b53400-1c16-11eb-938b-8335100d204f.png)

![image](https://user-images.githubusercontent.com/13303659/97796121-ea423d80-1c16-11eb-9768-c16ac67e4509.png)

1-pamac-aur
2-rclone-browser
