### ISSUE TITLE
[Icon request] system-reboot, system-shutdown, system-lock-screen, system-log-out

### ISSUE THREAD

**Issue by epsilon-0** [EliverLara/candy-icons#195]
- **App Name:** system standard operations
- **Icon Name:** system-reboot.svg, system-shutdown.svg, system-lock-screen.svg, system-log-out.svg
- **Description:** reboot, shutdown, lockscreen, log out.
- **Webpage (optional):** 
- **Original Icon:** 
https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/tree/master/Adwaita/256x256/legacy/

![Adwaita_256x256_legacy_system-lock-screen](https://user-images.githubusercontent.com/8932410/98856972-62391080-242c-11eb-8a08-86e947e54baf.png)
![Adwaita_256x256_legacy_system-log-out](https://user-images.githubusercontent.com/8932410/98856978-6402d400-242c-11eb-9713-a59a277cb2f7.png)
![Adwaita_256x256_legacy_system-shutdown](https://user-images.githubusercontent.com/8932410/98856980-649b6a80-242c-11eb-89d5-09313936e0c5.png)

Github doesn't let me upload reboot icon, it is here https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/raw/master/Adwaita/scalable/actions/system-reboot-symbolic.svg

**Comment by arnauddupuis** [comment]
I think they are part of the theme, in KDE Plasma I have that:
![image](https://user-images.githubusercontent.com/787155/99203086-456f4680-2766-11eb-8482-10aa2cd108a0.png)

And the logout screen looks good to:
![image](https://user-images.githubusercontent.com/787155/99203128-5d46ca80-2766-11eb-9e1e-9ce46924fa0b.png)

**Comment by epsilon-0** [comment]
Interesting, I'm curious why it didn't appear for me. 
I've not been able to find these icons in the git repository as well.
The names should have been the ones from the post title, as those are the generic names used.
Maybe a symlink is all that is needed? I am not sure what the base icon names are though.

**Comment by arnauddupuis** [comment]
I have no idea. To be honest, I installed the icons from Plasma GetHotNewStuff widget. Maybe it's doing some linking wizardry being my back.

**Comment by epsilon-0** [comment]
Yes, I am still unable to find them here.
Would love to know if @EliverLara has the answer :heart:

**Comment by epsilon-0** [comment]
@EliverLara 
Thank you so much!! :heart:
