### ISSUE TITLE
[Feature request] Provide *.ico and *.png releases for Windows

### ISSUE THREAD

**Issue by askfriends** [EliverLara/candy-icons#197]
hi;

first of all thanks a ton for this wonderful icon package.

I have download it to use in dock, but when i cant find .ico or .png files inside the download, all i can see is .svg files and i cant use them to replace icons in my dock, so will you add .ico files too in download package?

it would be nice if you post download link in github readme too.

**Comment by ratijas** [comment]
This icon set is designed for Linux systems, which generally don't use .ico at all. PNG files could be generated from SVG by sacrificing file size and resolution / image quality. Why would you want to do that? The package as it is was specially designed to be installed via system package manager or KDE «Get New Hot Stuff» plugin. What is (was) your use case? Which docking software does not support standard SVG icons?

**Comment by askfriends** [comment]
> This icon set is designed for Linux systems, which generally don't use .ico at all. PNG files could be generated from SVG by sacrificing file size and resolution / image quality. Why would you want to do that? The package as it is was specially designed to be installed via system package manager or KDE «Get New Hot Stuff» plugin. What is (was) your use case? Which docking software does not support standard SVG icons?

bcoz want to use on windows pc

**Comment by ratijas** [comment]
> bcoz want to use on windows pc

How? Like, manually setting icon path of each exe? I'm just not aware of any Windows centric solution for icon theming.

But sure, you can always use tools like imagemagic to automatically convert them all in batch.

**Comment by ratijas** [comment]
Then again, icons used inside Windows applications are usually baked in at compile time into executables as resources. They are not standardized, and trying to override them one by one would be a waste of time, and even after that they probably won't blend in very well with whatever the current theme is.

**Comment by askfriends** [comment]
> Then again, icons used inside Windows applications are usually baked in at compile time into executables as resources. They are not standardized, and trying to override them one by one would be a waste of time, and even after that they probably won't blend in very well with whatever the current theme is.

there is app which makes excutable .exe icon packager, i intend to use with that and most probably i want to use some icons to show on my desktop dock, i would need not more than 10 icons there. So if you could make .ico files it would be great bcoz these look awesome
