### ISSUE TITLE
Some icons not changing

### ISSUE THREAD

**Issue by dto26** [EliverLara/candy-icons#210]
First off, this is my favorite full icon pack!! I also love your Sweet theme! A few applications are keeping their default icons. I am wondering if you know a solution?

vscode,
atom,
androidstudio,
discord,
and Arduino IDE

**Comment by Smail** [comment]
Do you use snap packages for those applications? Snap uses hard-coded file paths for icons. There are two solutions to this, either edit the desktop files directly in `/var/lib/snapd/desktop/applications` and change the `Icon` key to a value this icon pack uses, i.e. set `Icon=discord` or copy the snap desktop files to `~/.local/share/applications` and edit them there. I prefer the second one.
