### ISSUE TITLE
The Download is Corrupted

### ISSUE THREAD

**Issue by letdowntown** [EliverLara/candy-icons#218]
I downloaded version 0.2.6 from [gnome-look](https://www.gnome-look.org/p/1305251/). Extracting the file gives me the following error:

```
letdowntown:~/Downloads$ tar -xf candy-icons.tar.xz 
xz: (stdin): Compressed data is corrupt
tar: Child returned status 1
tar: Error is not recoverable: exiting now

```

**Comment by bree29** [comment]
Hello ! Did you mean 0.2.6 ?
I do not have any issue to extract the .tar.xz from your link, the `v` flag give me all the listed files without any error.
The corruption must come from you while you were downloading the file.

**Comment by letdowntown** [comment]
That's weird but it seems to be working now. 

OP edited to reflect the correct version.
