### ISSUE TITLE
Please Add

### ISSUE THREAD

**Issue by TechnicSmile** [EliverLara/candy-icons#22]
Is it possible for you to link to all of the images for each of the icons. I find your designs stunning and would love to implement it on my windows computer. :)

**Comment by EliverLara** [comment]
Hi, What do you mean? I'm sorry I have not understood well

**Comment by TechnicSmile** [comment]
I was just asking to see if it was possible to get the icon file images because I am using windows.

**Comment by EliverLara** [comment]
This repo actually contains the `.svg` images, I don't know what is the icon format for windows but you could easily convert the `.svg` to any other format
