### ISSUE TITLE
[Icon Request] VirtualBox, Nextcloud, etc.

### ISSUE THREAD

**Issue by YamiYukiSenpai** [EliverLara/candy-icons#23]
Would it be possible for you to add icons for:

- [x] Nextcloud
  - [ ] Folders
  - [x] Application
- [x] VirtualBox
- [x] LibreOffice start center
- [x] OnlyOffice
- [x] Gaming desktop icon (`preferences-desktop-gaming`)
- [x] Shotwell
- [x] Lutris
- [x] KTorrent
- [x] Games folder (`folder-games`)
- [ ] QOwnNotes

**Comment by EliverLara** [comment]
I have already added some of the icons, Could you provide some example of the remaining icons?

**Comment by YamiYukiSenpai** [comment]
Like icon examples?
* Lutris
  ![image](https://user-images.githubusercontent.com/13153124/68506690-25927200-0238-11ea-9755-b5e54417fbb2.png)

* OnlyOffice
  ![image](https://user-images.githubusercontent.com/13153124/68506686-20352780-0238-11ea-885b-1b42454f6270.png)
