### ISSUE TITLE
[Icon request] Flameshot

### ISSUE THREAD

**Issue by zachjmurphy** [EliverLara/candy-icons#230]
- **App Name:** flameshot
- **Icon Name:** flameshot
- **Description:** Powerful yet simple to use screenshot software.
- **Webpage (optional):** https://flameshot.org/
- **Original Icon:**

    

![](https://linuxmasterclub.com/wp-content/uploads/2020/11/Flameshot-logo.png)

**Comment by serpro69** [comment]
This icon is already part of the icons set - https://github.com/EliverLara/candy-icons/blob/master/apps/scalable/flameshot.svg

**Comment by zachjmurphy** [comment]
Okay, Thanks. I will Close this Issue.
