### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by MurdeRMelodY** [EliverLara/candy-icons#231]
Is a discord icon included in candy-icons?

**Comment by serpro69** [comment]
https://github.com/EliverLara/candy-icons/blob/master/apps/scalable/discord.svg

**Comment by MurdeRMelodY** [comment]
I'm pretty new to linux, how do I apply this?

**Comment by darkbaboon** [comment]
Linux is about freedom of choice...so it depends of your current desktop environment!

Basically, you download and install manually the set of icons from here : www.opendesktop.org/p/1305251/ or automatically if the icons set is available as package for your linux distribution, then you select it with the settings manager of your desktop environment.

**Comment by MurdeRMelodY** [comment]
I'm currently trying out kde plasma on arch linux.
