### ISSUE TITLE
[Question] Snap integration

### ISSUE THREAD

**Issue by felipedelta0** [EliverLara/candy-icons#236]
Hello, I've noticed some of my apps installed with snap doesn't change the icon. I'll try to install it as apt or deb to check, but my question is: does the icons of snap packages change as well? Or doesn't have integration?

I'm using Ubuntu 20.10.

**Comment by EliverLara** [comment]
Hi, applications installed via snap have hardcoded path to icons, so you must manually change that, please take a look to #72 , #76 or #79.
