### ISSUE TITLE
[Icon request] 

### ISSUE THREAD

**Issue by jbingram** [EliverLara/candy-icons#241]
Hi there. Thx for your awesome work. Much appreciated. 
Here is a list of flatpak apps who seem not to work or not have been designed for the icon set:

- [x] Shortwave
- [x] Firefox
- [ ] Setzer
- [x] Dialect (moved to https://github.com/EliverLara/candy-icons/issues/378)
- [ ] Usage
- [ ] Glimpse
- [x] Jami
- [ ] Jitsi
- [x] Maps
- [ ] Parental control
- [ ] Cointop
- [ ] Banking
- [ ] Flatseal
- [x] Libreoffice apps (but weirdly the icon for the generic libreoffice launcher works)
- [ ] Video downloader
- [ ] Forklift
- [x] Easy tag
- [ ] Vector slicer
- [ ] Curtail
- [ ] Komikku
- [x] Feeds
- [ ] Giara
- [ ] News Flash

**Comment by ratijas** [comment]
Hi, I triaged the list as best as I could, however some app names are rather generic (such as "Dialect" and "Usage" and "Banking") so they need some clarifications: descriptions, links, icons names and original icons. Also note that generally flatpak apps don't play well with custom icon themes. For other X11 related workarounds please see https://github.com/EliverLara/candy-icons/issues/293 and https://github.com/EliverLara/candy-icons/issues/344.

**Comment by m1karii** [comment]
@ratijas Dialect is being tracked here: https://github.com/EliverLara/candy-icons/issues/378
