### ISSUE TITLE
[Icon Request] Plasma Logo

### ISSUE THREAD

**Issue by codewing** [EliverLara/candy-icons#242]
I would love to use the Plasma Logo as a launcher icon. 

Bonus question: Is there a "tutorial" on how to adapt the color theme?

The base SVG could be this:
https://kde.org/stuff/clipart/logo/plasma-logo-monochrome.svg

From here
https://kde.org/stuff/clipart/

**Comment by BoxFoxCode** [comment]
I'm not sure what to name these or if they actually have a theme placement (so made an arbitrary repo for spare things creation), but here's a few based off of the color logo clipart but with the color gradients recreated in Inkscape based off of the icon for Darktable, OBS, and one of the KDE apps.

They'll maybe kinda fit in? Maybe should mark a rounded one? There there are some icons with square corners.

https://github.com/BoxFoxCode/arbitrary-icons/tree/master/candy-icons

**Comment by codewing** [comment]
Looking really great even though not really matching the theme of bold outlines but I like it anyway :)
But I think this might be the logos issue.. Maybe the classic "KDE Logo" is better suited for this icon style?

![image](https://user-images.githubusercontent.com/12066466/108819795-9390b300-75bb-11eb-94c1-444484e12a36.png)
Anyway I like it a lot, thank you so much!

If you want me to try out the rounded one just add it and I can test it :)
