### ISSUE TITLE
Cant get VS Code Icon To Work??

### ISSUE THREAD

**Issue by Fraser-Hobbs** [EliverLara/candy-icons#248]
![screenshot](https://user-images.githubusercontent.com/72457419/108126780-243e2f00-70a2-11eb-9571-8005ef607749.png)

vscode was installed using `sudo snap install code --classic`

Not sure how to fix this any help would be apprechiated and also wondering if there is a discord icon?

**Comment by Tesseeaye** [comment]
Rule number 3 for requesting icons is "The app is not installed by snap (the snap packages have hardcoded paths to icons)" which would explain why yours isn't working. You're using the snap install. I'm using the Flatpak version of VS Code and I see it's custom icon.
![image](https://user-images.githubusercontent.com/30505698/108594967-1bbc5180-734b-11eb-85e4-98e13d51d595.png)
