### ISSUE TITLE
[Icon request]  LibreWolf, Hyperspace, Element Desktop, NoiseTorch, GreenWithEnvy, Dolphin, PCSX2, Pamac

### ISSUE THREAD

**Issue by ThisNekoGuy** [EliverLara/candy-icons#250]
- **App Name:** LibreWolf
- **Icon Name:** librewolf
- **Description:** A fork of FireFox
- **Webpage (optional):** https://librewolf-community.gitlab.io/
- **Original Icon:**
    
![LibreWolf-logo](https://user-images.githubusercontent.com/28468662/108958247-9eeee780-766a-11eb-929d-6a38c8c3c4bc.png)

- **App Name:** Hyperspace
- **Icon Name:** hyperspace
- **Description:** A mastodon chat client
- **Webpage (optional):** https://aur.archlinux.org/packages/hyperspace-bin/
- **Original Icon:**
![hyperspace](https://user-images.githubusercontent.com/28468662/110192603-ff2e1800-7e26-11eb-8475-7b7c9a83a6c3.png)
Past icon used to be squircle:
<img width="512" alt="hyperspace" src="https://user-images.githubusercontent.com/28468662/108958916-8e8b3c80-766b-11eb-9c89-38f756f3e623.png">

- **App Name:** Element
- **Icon Name:** io.element.Element
- **Description:** A matrix chat client
- **Webpage (optional):** https://element.io/
- **Original Icon:**
![element](https://user-images.githubusercontent.com/28468662/108959546-77008380-766c-11eb-86b4-562e751586be.png)

- **App Name:** NoiseTorch
- **Icon Name:** noisetorch
- **Description:** Creates a virtual microphone that suppresses noise, for any application.
- **Webpage (optional):** https://github.com/lawl/NoiseTorch
- **Original Icon:**
![noisetorch](https://user-images.githubusercontent.com/28468662/108959828-e1192880-766c-11eb-827f-ca375d464a88.png)

- **App Name:** GreenWithEnvy
- **Icon Name:** com.leinardi.gwe
- **Description:** Provides information, controls the fans and overclocks your NVIDIA video card
- **Webpage (optional):** https://gitlab.com/leinardi/gwe
- **Original Icon:**
![com leinardi gwe](https://user-images.githubusercontent.com/28468662/108960153-5dac0700-766d-11eb-9b8d-ce1b7d297d13.png)

- **App Name:** Dolphin
- **Icon Name:** dolphin-emu
- **Description:** Wii/GameCube emulator
- **Webpage (optional):** https://dolphin-emu.org/
- **Original Icon:**
![dolphin-emu](https://user-images.githubusercontent.com/28468662/108960520-f3479680-766d-11eb-8025-3aa8e49913b5.png)

- **App Name:** PCSX2
- **Icon Name:** PCSX2
- **Description:** Playstation 2 emulator
- **Webpage (optional):** https://pcsx2.net/
- **Original Icon:**

![pcsx2-logo](https://cdn.steamgriddb.com/logo/4ff792cd7f1132cdce40f2da0c437ee4.png)
- **App Name:** Pamac
- **Icon Name:** system-software-install
- **Description:** Arch Linux graphical front-end for the pacman package manager
- **Webpage (optional):** https://gitlab.manjaro.org/applications/pamac
- **Original Icon:** (Screenshot)
![pamac](https://user-images.githubusercontent.com/28468662/109062934-79042a00-76e0-11eb-9cc7-0eb968548a67.png)

**Comment by thibaultmol** [comment]
Seems like the Riot icon is still being used for Element (new name of Riot since a couple years ago)
