### ISSUE TITLE
[Icon Request] Spotify

### ISSUE THREAD

**Issue by eight85** [EliverLara/candy-icons#252]
It would be nice to have an icon for spotify

**Comment by eight85** [comment]
https://www.spotify.com/fr/download/linux/

**Comment by vegabook** [comment]
![image](https://user-images.githubusercontent.com/3780883/110471338-f01fc200-80d3-11eb-945d-cf6db616f9dc.png)

**Comment by codewing** [comment]
I think there is one already for spotify
https://github.com/EliverLara/candy-icons/blob/master/apps/scalable/Spotify.svg

**Comment by vegabook** [comment]
> I think there is one already for spotify
> https://github.com/EliverLara/candy-icons/blob/master/apps/scalable/Spotify.svg

@codewing same as for Slack when I clone this repo, of if I download from gnomedesktop.org, I don't get my spotify icon changing. 

https://github.com/EliverLara/candy-icons/issues/253#issuecomment-800311492

**Comment by EliverLara** [comment]
Hi an icon already exists for the requested app, please make sure the app is not installed via snap (the snap packages have hardcoded paths to icons) so you must manually change that, please take a look to #72 , #76 or #79.
