### ISSUE TITLE
[Icon request] Slack

### ISSUE THREAD

**Issue by vegabook** [EliverLara/candy-icons#253]
- **Slack**
- **Icon Name:** Snap installation so can't find it
- **Description:** Slack Icon
- **Webpage (optional):** https://slack.com/intl/en-gb/
- **Original Icon:**
    
![image](https://user-images.githubusercontent.com/3780883/110471243-d2525d00-80d3-11eb-897c-0d4024e114a0.png)

**Comment by codewing** [comment]
There should be already one for slack
https://github.com/EliverLara/candy-icons/blob/master/apps/scalable/com.slack.Slack.svg

**Comment by vegabook** [comment]
@codewing if I install via gnomedesktop.org, or if I clone this repo, my slack icon does not change. Any hint?

**Comment by EliverLara** [comment]
Hi an icon already exists for the requested app, please make sure the app is not installed via snap (the snap packages have hardcoded paths to icons) so you must manually change that, please take a look to #72 , #76 or #79.
