### ISSUE TITLE
MimeType Icons

### ISSUE THREAD

**Issue by Glasket** [EliverLara/candy-icons#257]
Are there any plans to add MimeType icons for files like .py, .md, and so on? Or is deferring to the Breeze theme for those considered the "correct" way of using the theme?

Just curious because while I don't mind the Breeze icons for mimes, it'd be nice to have the consistency of a single unified style across all of the icons.

**Comment by quantum-unicorn** [comment]
I'm also curious about this. I implemented mimetypes with a couple generic icons in my fork and created a pull request some months ago. I don't know if I did it correctly though.

**Comment by EliverLara** [comment]
I just merged @quantum-unicorn 's pull request as a starting point for mimetype icons.
