### ISSUE TITLE
[Icon request]  pcmanfm file manager

### ISSUE THREAD

**Issue by open-sorcerer64** [EliverLara/candy-icons#260]
pcmanfm
every icon except folders
file manager in raspberry pi os
Please add raspberry pi os complete support

**Comment by EliverLara** [comment]
Please provide the required information to request an icon.

**Comment by ratijas** [comment]
pcmanfm itself uses `system-file-manager` icon which is available in this theme: https://github.com/EliverLara/candy-icons/blob/master/apps/scalable/system-file-manager.svg

If you have specific requests for other icons, please provide their names one by one (even if in a single big icon request issue).
