### ISSUE TITLE
[Icon request]  Various missing icons

### ISSUE THREAD

**Issue by tanshoku** [EliverLara/candy-icons#262]
![missing_icons](https://user-images.githubusercontent.com/66687139/116940401-4d537200-ac44-11eb-9027-7ca1508e41e5.png)

EDIT: on `Graphic Tablet`, the icon should be called `preferences-desktop-tablet`, sorry for the typo

**Comment by makerio90** [comment]
transmission already exists

**Comment by tanshoku** [comment]
> transmission already exists

Yes, but the icon is not applied to Transmission Remote, since it requires the icon to be called `transmission-remote-gtk`, so a symlink to the actual icon is needed

**Comment by makerio90** [comment]
oh

**Comment by EliverLara** [comment]
- [ ] tomboy
- [ ] mp3splt
- [ ] xscreensaver
- [ ] transmission remote
- [ ] psensor
- [ ] grafx2
- [ ] apper
- [ ] skanlite
- [ ] tagainijisho
- [ ] fcitx5
- [ ] mkvtollnix
- [ ] wacom tablet finder
- [ ] konqueror
- [ ] development
- [ ] science
- [ ] system tools
- [ ] education
