### ISSUE TITLE
[Icon request] Parrot panel menu icon

### ISSUE THREAD

**Issue by jakbin** [EliverLara/candy-icons#266]
Parrot panel menu icon 

Please add this . I am using parrot os. It's showing foot icon, that's not looking good.

**Comment by EliverLara** [comment]
Could you provide an example(maybe default icon) of the requested icon?

**Comment by jakbin** [comment]
Ok I will provide

**Comment by jakbin** [comment]
this is how look my default Parrot panel menu icon
![2021-07-24_10-01](https://user-images.githubusercontent.com/65591973/126857470-45eff404-0179-40ae-9d5c-8311704a0afa.png)

amd this is how look Parrot panel menu icon in candy icons 

![2021-07-24_10-02](https://user-images.githubusercontent.com/65591973/126857494-6d7e6513-b1f3-4939-9f46-9c00458cddd7.png)

**Comment by jakbin** [comment]
example icon :- 
![parrot](https://user-images.githubusercontent.com/65591973/126857670-7b91e6e0-e735-45a1-a53a-6518f3d3909a.png)
