### ISSUE TITLE
Can I contribute ?

### ISSUE THREAD

**Issue by tomaszdrozdz** [EliverLara/candy-icons#273]
I have cloned repo:

    * remote origin  
      Fetch URL: https://github.com/EliverLara/candy-icons.git  
      Push  URL: https://github.com/EliverLara/candy-icons.git
      HEAD branch: master
      Remote branch:
        master tracked
      Local branch configured for 'git pull':
        master merges with remote master
      Local ref configured for 'git push':
        master pushes to master (up to date)`

Created branch firefor_flatpak and add link: org.mozilla.firefox.svg -> ./firefox.svg

I want to push (then create pull request), but:  

    > git push --set-upstream origin firefox_flatpak
    Username for 'https://github.com': tomaszdrozdz
    Password for 'https://tomaszdrozdz@github.com': 
    remote: Permission to EliverLara/candy-icons.git denied to tomaszdrozdz.
    fatal: unable to access 'https://github.com/EliverLara/candy-icons.git/': The requested URL returned error: 403

Do you allow for making pull request, or should you give me "rights" for it ?

**Comment by Summon528** [comment]
You will have to fork the repo first

**Comment by moeinmhzg** [comment]
@Summon528 is right. right now you'r trying too directly push to this repo which you don't have permission to access. so you have to fork it first to have a copy which it's owner is you. then you can push your commits to your own copy version of the project an then you can make a PR.

**Comment by ratijas** [comment]
The `org.mozilla.firefox.svg` icon link has been added in [f3ecbb5](https://github.com/EliverLara/candy-icons/commit/f3ecbb5a8a0fe491ee4de89c40a41bc6b069748b).
