### ISSUE TITLE
[Icon change process] 

### ISSUE THREAD

**Issue by akjha96** [EliverLara/candy-icons#281]
Hi, Can you let us know how can we change Folder icons in File Explorer. 

I want to apply a different icon for the Folder as shown in the 4th screenshot on the official gnome look site. 

Link: https://www.gnome-look.org/p/1305251/

All my other icons are perfect. I just want to know how to change the ones in File Explorer.

Attached Screenshots
![Folder icons in file explorer](https://user-images.githubusercontent.com/29950848/120079243-a3df8f00-c0d0-11eb-98f2-c2ee61edcaaa.png)
![Other icons perfect](https://user-images.githubusercontent.com/29950848/120079244-a4782580-c0d0-11eb-8140-df2418fb1fbc.png)
![What I want](https://user-images.githubusercontent.com/29950848/120079245-a5a95280-c0d0-11eb-8508-ec56abde9c17.png)

**Comment by EliverLara** [comment]
1. Download the [sweet folder theme](https://www.opendesktop.org/p/1284047/)  you want, and do the following:

- Edit the `index.theme` file and define the `inherits` key with your favorite icon theme e.g:

`Inherits=candy-icons,ubuntu-mono-dark,Mint-X,elementary,gnome,hicolor
`

2. Using a tweak-tool or terminal set your system icons to use the recently downloaded folder theme.
