### ISSUE TITLE
Azure Data Studio Icon no longer working

### ISSUE THREAD

**Issue by LarnuUK** [EliverLara/candy-icons#282]
For some reason since I updated Azure Data Studio to version 1.29.0 the icon in the pack is no longer being used; it is using the default icon shipped with the application. As far as I can tell the application name hasn't changed, it's still `azuredatastudio` so not sure why it's not being picked up.

**Comment by EliverLara** [comment]
Hi, have you checked if the `icon` entry in the application's .desktop file has changed?
