### ISSUE TITLE
Remmina icon usage

### ISSUE THREAD

**Issue by comradekingu** [EliverLara/candy-icons#283]
The candy-icons version does exactly what I thought was needed, so want to try it out and see what others think.

![Remmina](https://user-images.githubusercontent.com/13802408/120792151-6007e200-c535-11eb-9422-b963336aab8f.png)

Tweaked the colours a bit, and removed the tool notice from the SVG.

I don't understand why the blue outer line doesn't line up with the inner elements, but right now I have spent all my effort trying to do colours (which I am really bad at).

Can you grant a GPLv2+ exception for its use in Remmina?

Candy-icons original:
![candyicons](https://user-images.githubusercontent.com/13802408/120792814-5fbc1680-c536-11eb-897a-3cb4fbccdfe0.png)

Remmina original:
![image](https://user-images.githubusercontent.com/13802408/120792600-110e7c80-c536-11eb-8f34-97887709454b.png)

**Comment by EliverLara** [comment]
Hi, if the icon fits your needs, feel free to use it.
