### ISSUE TITLE
FIREFOX ICON 

### ISSUE THREAD

**Issue by guywhoreportsissues** [EliverLara/candy-icons#295]
I don't like the firefox icon which comes up in the candy icons. Which comes with the sweet theme. It's misleading because it is not the actual firefox logo. It's just a logo for the masterbrand. i.e a logo for a collection of products like firefox monitor firefox lockwise etc It's one logo for all of them.
BUT, IT IS NOT THE FIREFOX LOGO. PLEASE FIX THE CANDY ICON ISSUE.

**Comment by ratijas** [comment]
What do you mean, again?  Monitor and Lockwise actually have different icons. Are you saying this candy theme reuses main Firefox icon for other Mozilla products?

**Comment by guywhoreportsissues** [comment]
> What do you mean, again? Monitor and Lockwise actually have different icons. Are you saying this candy theme reuses main Firefox icon for other Mozilla products?

In latte dock firefox uses the wrong logo. Correct it to the fox with the purple globe. If you want to know more:- https://blog.mozilla.org/en/products/firefox/the-fox-is-still-in-the-firefox-logo/

**Comment by ratijas** [comment]
I see. That makes perfect sense. Thanks for the link.

On the other hand, these candy icons are intentionally over-simplified, leaving only outlines of general shapes and some resembling gradient colors. I'd say it's probably for people who are already familiar with design and original icons. Not sure, if it is possible to make 'true' firefox logo that would still fit the description above.

Meanwhile, you can just delete all firefox icons files from your installed copy of candy theme, reset icons cache and reboot.

**Comment by guywhoreportsissues** [comment]
> I see. That makes perfect sense. Thanks for the link.
> 
> On the other hand, these candy icons are intentionally over-simplified, leaving only outlines of general shapes and some resembling gradient colors. I'd say it's probably for people who are already familiar with design and original icons. Not sure, if it is possible to make 'true' firefox logo that would still fit the description above.
> 
> Meanwhile, you can just delete all firefox icons files from your installed copy of candy theme, reset icons cache and reboot.

I understand, By the way I think you can just draw an outline of the firefox icon. You can take Beautyline icon theme as an example. 
Firefox icon (Beautyline icon theme) 

![Screenshot_2021-07-19_21-43-26](https://user-images.githubusercontent.com/86945563/126192607-34c7bdf5-b562-442a-8a4e-64bc790097ae.png)
link to the beautyline icon theme
https://store.kde.org/p/1425426/
