### ISSUE TITLE
When opening Fritzing, a new tab opens in the dock and the icon no longer matches up with the one used to launch. 

### ISSUE THREAD

**Issue by Lekua** [EliverLara/candy-icons#296]
The title sounds a little confusing, it even makes me. So I'll try to explain, basically I got Fritzing from the Pop!_Shop. In my dock (Planks) and in the applications window it shows up perfectly fine. With the correct icon and everything, but when you open it. A new "tab" opens up, and it has the default Fritzing icon. This was also happening when I reinstalled Firefox, from using their install script and installing from the Pop Store. 

I tried to fix this issue with Main Menu, thinking it was just another application and I could change it's icon through there. Sadly there was no Fritzing application with the icon I see after starting the program. The only thing I could think of is building it from source may fix it. As this has happened before, for example Spotify from the Pop Shop will do the same thing. Starting a song will open a new "tab" and display a ? as its icon. I haven't tried building it from source, as I've never had much success with it and wanted to ask here before I try anything. 

Thanks!

**Comment by ratijas** [comment]
It sounds like you are likely facing issues with runtime detection of application icons on X11. See #293 and #344 for possible workarounds.

Feel free to reopen if that's not the case.
