### ISSUE TITLE
Possibility for an alternative 'firefox' icon?

### ISSUE THREAD

**Issue by Qqwy** [EliverLara/candy-icons#3]
![firefox_icon-screenshot](https://user-images.githubusercontent.com/5345745/58761951-2ff26680-854a-11e9-869a-c4911dfa8229.png)
On small sizes, the 'Firefox' icon is very difficult to recognize as firefox, because its lines are not resized as well as other icons. I think the current icon has too much detail.

Would it be possible to have another (or an alternate) firefox icon?

**Comment by eiglow** [comment]
I have the same issue, it seems like the lines are too thin and there is too much detail compared to all the other icons, it doesn't really fit in.

**Comment by Weetile** [comment]
It looks like in the latest version there is a new Firefox icon!

![image](https://user-images.githubusercontent.com/7700383/67158167-a1318b00-f32c-11e9-9422-309eaec5aa6d.png)
