### ISSUE TITLE
[Icon request] XFCE Panel icons

### ISSUE THREAD

**Issue by Homelessguy42** [EliverLara/candy-icons#302]
Can you please add icons for the xfce status panel? I attached a screenshot of how it looks currently with the theme applied
![panel](https://user-images.githubusercontent.com/67023264/126908079-f4dcf49a-69b0-4442-a0fd-45e57b2876b1.png)

**Comment by Aperson2131** [comment]
I also have this problem. I think those icons are under status/symbolic.
