### ISSUE TITLE
Button icons are too dark

### ISSUE THREAD

**Issue by octylFractal** [EliverLara/candy-icons#332]
I'm not sure what changed this, but I recently updated my system and discovered that this icon theme makes my buttons look like this:
![buttons](https://url.octyl.net/9jrr-8i-b056dmsjb5g9)
instead of being lighter, like this (Breeze Dark):
![buttons again](https://url.octyl.net/8xwnb88r4sqmh3z29wtr)

I suspect this may have something to do with changes in Plasma 5.88, which was part of my recent system update. Let me know if you need any other details.

**Comment by 20manas** [comment]
I'm having the same problem. The fix may be #330.

**Comment by octylFractal** [comment]
I installed and tested the fix locally, and it indeed does fix the issue.

**Comment by EliverLara** [comment]
Thanks for reporting! it was fixed with #330
