### ISSUE TITLE
Weird artifact in Discord Canary icon

### ISSUE THREAD

**Issue by xenorio** [EliverLara/candy-icons#334]
For some reason, the Discord Canary icon has an artifact next to the left eye.
![image](https://user-images.githubusercontent.com/39472201/142325644-2e38597a-d57d-4379-aab4-0a2b43cc764f.png)
However, this is not present in [apps/scalable/discord-canary.svg](https://github.com/EliverLara/candy-icons/blob/master/apps/scalable/discord-canary.svg)
I do not have this problem with any other icons so far. No idea how this can even happen.

**Comment by ratijas** [comment]
Hi, @Xenorio, what is your desktop environment, software versions etc.? If you use KDE, you can copy everything from «About this System» in «Info Center» app.

Where is that screenshot taken on? Plasma panel / Latte dock / some other docking software?

**Comment by ratijas** [comment]
The icon itself looks pointy on its bottoms, but there's indeed nothing like dots on your screenshot.

![Icon preview in Cuttlefish](https://user-images.githubusercontent.com/6737986/152590777-1d09ae89-2d63-4be3-b016-0474df294d08.png)

**Comment by Xenorio** [comment]
i'm using gnome. the screenshot is just from the dock in the applications panel.

![image](https://user-images.githubusercontent.com/39472201/152633792-4e7541e2-4ae1-49a5-ad35-d2dc76d31923.png)
