### ISSUE TITLE
App icons are not changing when they are downloaded from Ubuntu Software

### ISSUE THREAD

**Issue by Craft-Man-1** [EliverLara/candy-icons#335]
Visual Studio Code, Discord, Zoom, and some other apps like these which are downloaded from _Ubuntu Software_ are in their original app icons. These app icons are not changing after using candy icons. But when I install these same programs from their official websites, then the icon changes. Such as when I download and install _Zoom_ from _Ubuntu Software_ the app icon doesn't change. But when I download and install the same app Zoom from _https://zoom.us/support/download_ website, the app icon changes.

**Comment by Xenorio** [comment]
The Ubuntu software store supports installing software through the snap package manager, so i think that's your problem. Because of sandboxing, snap uses its own .desktop files and icon system, which is not supported by this icon pack (or any icon packs for that matter)

You have 2 options here

1: Don't install software through snap (You can select which package manager to use in Ubuntu Software, or just directly use apt from the terminal)

2: Copy the .desktop file that snap has created from ``/var/lib/snapd/desktop/application/`` to ``/usr/share/applications/`` and change its icon variable to what it's called in the icon pack. Do not delete the original desktop file. The copy has higher priority than the original.

[Source for this answer](https://askubuntu.com/questions/1278025/how-to-change-the-icons-of-snap-programs)

**Comment by acgollapalli** [comment]
Ubuntu has deprecated .deb sources for some programs, including chromium. I expect snap may very well end up becoming the default for a lot of software people use, if it hasn't already.

**Comment by Xenorio** [comment]
> Ubuntu has deprecated .deb sources for some programs, including chromium. I expect snap may very well end up becoming the default for a lot of software people use, if it hasn't already.

cool story bro. doesn't make it more compatible, so it's unrelated to this.

**Comment by acgollapalli** [comment]
> so it's unrelated to this.
It's entirely related to this, because it means your option 1 of using apt-get is not feasible. apt-get defaults to using snap.

**Comment by Xenorio** [comment]
> apt-get defaults to using snap

it does not. also there are other package managers than apt.

**Comment by acgollapalli** [comment]
try `apt install chromium-browser` and see what happens.

**Comment by Xenorio** [comment]
> try `apt install chromium-browser` and see what happens.

i most certainly will not, as i already know the outcome, which would be something along the lines of ``apt: command not found``

but i'm not saying that apt does not install software through snap, i'm saying it doesn't default to it. chromium is an exception.

all i'm saying really is if you have compatibility issues with software, you can go the easy way of not using it, or the hard way of working around the incompatibility, depending on what you feel comfortable with. you **can** ditch snap on ubuntu. it's a gnu/linux system. get a different package manager if you don't like the one you have.

honestly i do not understand why this argument would even unfold over some goddamn icons not showing up

**Comment by zedus1** [comment]
> 

hello, my `slack.desktop` in `/usr/share/applications/` but it isn't work. please help me.
![image](https://user-images.githubusercontent.com/91052454/144337756-96b48ded-45bf-478d-b5e5-62ad8256fc00.png)
![image](https://user-images.githubusercontent.com/91052454/144338211-d3e31dc0-bc67-4af4-843f-0bd3107751a6.png)

git kraken and sublime text too

**Comment by zedus1** [comment]
I don't install software through snap. 
![image](https://user-images.githubusercontent.com/91052454/144430555-bafde617-e521-484b-9fef-ed38a8d09b11.png)
thank you answer my question

**Comment by Xenorio** [comment]
> I don't install software through snap.

In that case, again, post the contents of the desktop file. Specifically the icon field. I am assuming that there's a direct link to an image file in there, which you would need to change to just say ``slack``, which is the name of it in this pack without the svg extension ([apps/scalable/slack.svg](https://github.com/EliverLara/candy-icons/blob/master/apps/scalable/slack.svg))

**Comment by zedus1** [comment]
> > I don't install software through snap.
> 
> In that case, again, post the contents of the desktop file. Specifically the icon field. I am assuming that there's a direct link to an image file in there, which you would need to change to just say `slack`, which is the name of it in this pack without the svg extension ([apps/scalable/slack.svg](https://github.com/EliverLara/candy-icons/blob/master/apps/scalable/slack.svg))

![image](https://user-images.githubusercontent.com/91052454/144531539-241316d9-d414-412b-beba-8665ddcf3ff4.png)
![image](https://user-images.githubusercontent.com/91052454/144531927-4809bd80-8e5e-4b04-a940-15467c3e8b24.png)
i chang line 7 png(old)->svg(new icon) 
but it only changes here
![image](https://user-images.githubusercontent.com/91052454/144532179-a4ada09e-2330-4d9e-bd42-a6750fca2478.png)
It's still the same here
![image](https://user-images.githubusercontent.com/91052454/144532232-4df0c527-ad03-4753-bf46-0e6455e05ccd.png)

**Comment by zedus1** [comment]
> 
UPDATEEEEEEEEEEEEEEEEEE
yesssss it work for me when i change the new icon is also png. thank you very much!

**Comment by EliverLara** [comment]
Hi please make sure the app is not installed via snap (the snap packages have hardcoded paths to icons) so you must manually change that, please take a look to #72 , #76 or #79.
