### ISSUE TITLE
VERY BEAUTIFUL. CAN YOU HELP ME?

### ISSUE THREAD

**Issue by zedus1** [EliverLara/candy-icons#345]
![image](https://user-images.githubusercontent.com/91052454/145135331-efa0e12d-89fe-477e-913b-86b5273d7fb8.png)
i find this terminal interface very nice, can someone tell me please? skull shape?

**Comment by EliverLara** [comment]
Hi, that is `gnome terminal` and I'm using `fish shell` with a custom prompt(skull).

**Comment by Lohith-profile** [comment]
question is answers this can be closed
