### ISSUE TITLE
Thunderbird

### ISSUE THREAD

**Issue by I-Vuk** [EliverLara/candy-icons#354]
Thunderbird mail is missing a icon

**Comment by ratijas** [comment]
Thunderbird mail is in the set: https://github.com/EliverLara/candy-icons/blob/master/apps/scalable/thunderbird.svg

If you are facing issues on X11 graphics system, please take a look at some available workarounds here: https://github.com/EliverLara/candy-icons/issues/293 and https://github.com/EliverLara/candy-icons/issues/344
