### ISSUE TITLE
[Icon request] KeeWeb

### ISSUE THREAD

**Issue by I-Vuk** [EliverLara/candy-icons#355]
- **App Name:** KeeWeb
- **Icon Name:** keeweb
- **Description:** Free cross-platform password manager compatible with KeePass
- **Webpage:** https://keeweb.info
- **Original icon:** ![keeweb](https://keeweb.info/img/logo.png)

**Comment by ratijas** [comment]
It failed to build on my Arch Linux, so I had to extract data from the official deb package.
