### ISSUE TITLE
Camera icon is abused too much

### ISSUE THREAD

**Issue by ratijas** [EliverLara/candy-icons#360]
Camera/Zoom icon is being reused / abused too much. Somehow in certain contexts it overrides all the zoom in / zoom out / reset zoom icons like on a screenshot below.

![Screenshot_20220118_000535](https://user-images.githubusercontent.com/6737986/149836984-5fa6e911-1654-4f59-b711-46b299be8b97.png)

**Comment by ratijas** [comment]
>  789f0bf 

Works perfectly, thanks! Zoom buttons are back to normal, while Zoom app is still customized.

**Comment by EliverLara** [comment]
@ratijas Thanks for reporting!

**Comment by ratijas** [comment]
Wait a sec. I'm not sure what's going on, but the issue still persists in Gwenview, after I have confirmed the fix for Ark. Both apps are based on Qt Widgets.

![Candy icons - gwenview zoom icon bug](https://user-images.githubusercontent.com/6737986/150700861-7833acbb-c7bb-4757-90f6-239f02af4549.png)

wat the heck is going on… Is there any icons cache that I should have probably cleared after manually deleting an icon?
