### ISSUE TITLE
[Icon request] 

### ISSUE THREAD

**Issue by aoeuidhtns0** [EliverLara/candy-icons#363]
screenshot

图标缺失
    missing icon, Icon is missing

图标缺失
    missing icon, Icon is missing

https://github.com/aoeuidhtns0/aaa/blob/main/Screenshot%20from%202022-01-28%2003-22-12.png

[screenshot.png](https://github.com/aoeuidhtns0/aaa/blob/main/Screenshot%20from%202022-01-28%2003-22-12.png)

**Comment by ratijas** [comment]
Hi, what's the name of the app? Which graphics system are you using (X11 or Wayland)?

**Comment by ratijas** [comment]
Doesn't seem like we are getting any more info from @aoeuidhtns0. Closing it, because it is not actionable as it is. Feel free to reopen with more details.
