### ISSUE TITLE
[Icon request] GammaRay (Qt runtime introspection tool, SDK tools category)

### ISSUE THREAD

**Issue by ratijas** [EliverLara/candy-icons#367]
Actually, looks quite good on its own, just needs a bit lightness to it because currently it blends in with Breeze color scheme on task manager panel.

- **App Name:** GammaRay
- **Icon Name:** `Icon=GammaRay`, exactly like that, Title Case.
- **Description:** Qt-application inspection and manipulation tool
- **Webpages:**
  - https://www.kdab.com/development-resources/qt-tools/gammaray/
  - https://github.com/KDAB/GammaRay/
- **Original Icon:**

https://github.com/KDAB/GammaRay/tree/master/ui/resources/gammaray

![GammaRay](https://user-images.githubusercontent.com/6737986/152594681-f97a5752-15ee-4502-b28e-3a28200b2cf3.png)

**Comment by ratijas** [comment]
@EliverLara Let me guess: you are using the "completed" label to indicate to yourself that you drew the icon, but it may not be published yet as you are batching them up for git push later?

**Comment by EliverLara** [comment]
@ratijas you're right, the completed label is just an indicator for me.

I would like to thank you for all the help you have provided as a collaborator and more for supporting the project with your sponsorship, that means a lot to me, thank you so much @ratijas !

**Comment by ratijas** [comment]
> @ratijas you're right, the completed label is just an indicator for me.

Just as I thought. Alright, I won't act on them then. FWIW I have just tweaked the labels' descriptions (they are visible on hover), some — to make them clearer, some — didn't really match each other at all.

> I would like to thank you for all the help you have provided as a collaborator and more for supporting the project with your sponsorship, that means a lot to me, thank you so much @ratijas !

Cheers! May it be the first of many! :)

Hope I did a decent job at triaging and stuff, so you could focus on what's more interesting and important.
