### ISSUE TITLE
Icon Submission (READ ME)

### ISSUE THREAD

**Issue by AceSardonyx** [EliverLara/candy-icons#370]
It seems like the owners aren't doing any of the requests so I am making my own and I will be providing them here as well as through discord at !Ace#2002 if asked
The ones I've made for the pack itself are Netflix and Notepad++
[Here's the first comment I made about notepad++](https://github.com/EliverLara/candy-icons/issues/239#issuecomment-1030762290)

I will be uploading all icons I make [here](https://drive.google.com/drive/folders/16_JpVILWHVAYyX_4ZMn27eYbVfAwv_Ze?usp=sharing)

(I thickened it so this isn't what it looks like :p) Preview:
![image](https://user-images.githubusercontent.com/77860646/152715707-74e85250-4e15-4e7f-a48e-5d5bf6f58b42.png)

**Comment by ratijas** [comment]
Hi, Ace! That's a very nice icon indeed :)

The owner doesn't have much free time, but he triages issues and implements requests once in a month or so. Why won't you submit a Pull Request to this repo? Feel free to contact me if you need any help or guidance!

**Comment by AceSardonyx** [comment]
Ohhhhh. I see, my bad.
Okay. I will upload the ones I make on that google drive link. Anyone can use em.
If I have a program without a candy icon, I usually just make one when I'm in study hall at school since I have free time there :)
Thanks :D

**Comment by ratijas** [comment]
That's a healthy proactive attitude. Let's upstream them! :)
