### ISSUE TITLE
[Icon Request] authy

### ISSUE THREAD

**Issue by TirthaNag13** [EliverLara/candy-icons#373]
Application Name : Twilio Authy
Icon name            : Twilio Authy
Application Description : Two factor authenticator app.
Original Icon 
![authy-logo-svg-vector](https://user-images.githubusercontent.com/99326134/153760583-1dfe6bb7-78ea-4f40-b54d-a9c037a1a619.svg)
Official Website : www.authy.com

**Comment by AlanJojo** [comment]
This is a snap application.
