### ISSUE TITLE
[Icon request] Text file

### ISSUE THREAD

**Issue by m1karii** [EliverLara/candy-icons#376]
I've found an icon (https://github.com/EliverLara/candy-icons/blob/master/mimetypes/scalable/text-x-generic.svg), could this be applied as text (`.txt`) file icon?

**Comment by ratijas** [comment]
Works for me

![Screenshot_20220312_013131](https://user-images.githubusercontent.com/6737986/157982862-f4964d3c-720f-4f78-adc1-25b029e2b609.png)

**Comment by m1karii** [comment]
> Works for me

oh, so it *is* supposed to be an icon of the textfile ...
well ... doesnt work for me. I use Manjaro with KDE Plasma. (what do you use?)
![image](https://user-images.githubusercontent.com/82673417/158034121-313ea283-3da4-4524-9ce7-7d548b9329c1.png)
this is screenshot from Desktop but it doesnt work in Dolphin either

**Comment by ratijas** [comment]
> what do you use?

Arch Linux + building KDE stuff directly from master.

No idea what went wrong in Manjaro land. Might depend on how did you install the icon pack. Try asking them for support?

**Comment by m1karii** [comment]
Figured it out. The issue was on *my* side.
