### ISSUE TITLE
[Icon request] Raspberry Pi Logo

### ISSUE THREAD

**Issue by m1karii** [EliverLara/candy-icons#377]
Title.
![image](https://user-images.githubusercontent.com/82673417/156936533-722e48c8-4440-46a0-9a0b-8f69658de989.png)

**Comment by ratijas** [comment]
> Title.

Comment.

Which app is that?

**Comment by m1karii** [comment]
not an app
its a "distributor"
like the ones below:
![image](https://user-images.githubusercontent.com/82673417/158033698-600ae73d-5288-4df6-b6a0-77d8377e5e79.png)
and although Raspberry Pi is HW there is also Raspberry Pi OS with the same logo ...

**Comment by ratijas** [comment]
We still need a proper icon name to act on this request. What's the canon logo icon name for Raspberry Pi OS? Where are those even used? I don't remember seeing any of them ever. Even the one on the "About this System" page is the default Arch Linux logo — not from candy icons pack — on my system.

**Comment by m1karii** [comment]
well its used as an icon for start menu in Raspberry Pi OS, and although idk what the name of this icon is,
the RPi logo is also used as an icon for 
- **App:** Raspberry Pi Imager
- **Icon:** `rpi-imager`
- **Install:** `sudo pacman -S rpi-imager`

**Comment by ratijas** [comment]
> well its used as an icon for start menu in Raspberry Pi OS, and although idk what the name of this icon is,

Can you upload a screenshot, please? Then we might be able to track down its usage in source code.

My KDE application launcher (technically called Kickoff) only shows Plasma icon by default, but can be configured manually to show anything else. So, I don't know what to look for.

**Comment by m1karii** [comment]
Here is a screenshot from stock Raspberry Pi OS desktop (from wikipedia as I currently don't have any RPi at hand):
![image](https://upload.wikimedia.org/wikipedia/commons/2/24/Rapberry_Pi_OS_Screenshot_2021-12-02_de.png)
