### ISSUE TITLE
[Icon request] PolyMC

### ISSUE THREAD

**Issue by Krutonium** [EliverLara/candy-icons#379]
- **App Name:** PolyMC
- **Icon Name:** org.polymc.PolyMC
- **Description:** A fork of MultiMC 
- **Webpage (optional):** https://polymc.org
- **Original Icon:** 
    
![org polymc PolyMC](https://user-images.githubusercontent.com/3945538/157198775-818f60e5-b817-401c-89f4-8099810719f6.svg)

**Comment by Motschen** [comment]
My PR (#391) that adds an icon for PolyMC has been merged, so this can be closed now.
