### ISSUE TITLE
Please revise "manjaro" icon

### ISSUE THREAD

**Issue by m1karii** [EliverLara/candy-icons#380]
When scaled the vertical lines in manjaro icon seem to have different thickness than the horizontal line
![image](https://user-images.githubusercontent.com/82673417/158033988-d363240f-6ac9-45b9-a43e-5f33b3813400.png)

**Comment by ratijas** [comment]
Hmm… Not a big fan of manjaro, but the icon should be pixel-perfect indeed.

**Comment by ratijas** [comment]
FWIW an official logo seem to be equally spaced:

https://manjaro.org/img/logo.svg
![logo](https://manjaro.org/img/logo.svg)

(technically it's called "green.svg", and they didn't even bother to clean it up from Inkscape meta even a bit, lol)

The "edges" are located at the following guidelines (in percents, or rather in 0..1 range of the full icon size):

- x:
  - 0.29168148285694073, 0.35365197217717453 (diff = 0.0619704893202338)
  - 0.6463645573496363, 0.7073145742751276 (diff = 0.06095001692549129)
- y:
  - 0.29168148285694073, 0.35365197217717453 (diff = 0.0619704893202338)

As we can see, the distance between adjacent guidelines is practically equal for all three gaps. So, now it's just a matter of aligning our icon's edges (1) to those values, and then (2) to the nearest pixels at <= 48px scale while maintaining equal distance.

**Comment by ratijas** [comment]
This is how they look like when laid out on top of each other. I did it with semi-transparent Inkscape window.

![Screenshot_20220313_012411](https://user-images.githubusercontent.com/6737986/158037109-02045a0d-c2f6-4593-96fb-905a2706bf0c.png)

Candy-icon version is narrower.
