### ISSUE TITLE
Ubuntu 22.04 LTS missing icons

### ISSUE THREAD

**Issue by Sleyana** [EliverLara/candy-icons#390]
Right now i can see missing the Firefox and the Spotify icon. 

I know for sure that on Ubuntu 20.04 they were there.

**Comment by cihatertem** [comment]
Snap application cannot use icon theme packages :/. Are there any ways to use icon themes for snap packages?

**Comment by Sleyana** [comment]
Im not a dev just a casual Linux user trying to avoid Billy G and Windows.

But i followed this instruction https://askubuntu.com/questions/1278025/how-to-change-the-icons-of-snap-programs

After that i opened the copied file and changed the icon path to your icons. Its a workaround for every snap package.

**Comment by ratijas** [comment]
I'm not much into technical details, but I heard snap is generally not a favorable app distribution format. If there're Flatpak versions, try those — at least they seem to be themeable just fine.

**Comment by RAinb0wStAr9938** [comment]
Or install the apps as a deb.
