### ISSUE TITLE
Application icon issue.

### ISSUE THREAD

**Issue by TheNukeLore** [EliverLara/candy-icons#394]
Not sure if Ive done anything wrong but it seems some applications have an issue with this icon set specifically, mostly the issues happen with Inkscape, any other icon theme seems to work but when candy icons are enabled i seemingly have issues.

candy icons:
![image](https://user-images.githubusercontent.com/56121120/174462776-dee3bee3-5fd0-4428-a05f-87f486bff078.png)

breeze:
![image](https://user-images.githubusercontent.com/56121120/174462795-d87fd371-2f95-4872-b498-5832529191e3.png)

running linux mint with kde. if more details are needed please ask. also not sure who would need to fix this, Inkscape or this project.

**Comment by EliverLara** [comment]
HI, This is cause candy-icons is supposed to work with dark themes.

**Comment by RAinb0wStAr9938** [comment]
If you can, try switching Inkscape to a dark theme.
