### ISSUE TITLE
Candy Icons won't update through Discover on KDE

### ISSUE THREAD

**Issue by MiguelGuthridge** [EliverLara/candy-icons#397]
Whenever I try to update candy icons, I get the following error:

![image](https://user-images.githubusercontent.com/31365175/175460602-e38ffcfa-b8a7-4df6-95f8-1952d3e5adfc.png)

The updating freezes and I can't cancel it without force killing Discover.

This issue only appears to be happening with Candy Icons, but perhaps other addons simply haven't had a chance to break yet

**Comment by ratijas** [comment]
See https://bugs.kde.org/show_bug.cgi?id=455540
