### ISSUE TITLE
Icons request

### ISSUE THREAD

**Issue by domenicoblanco** [EliverLara/candy-icons#4]
Hi, first of all thanks for this awesome icon pack!
Could you add icons for:

- [x] Telegram
- [x] Gnome Tweak Tool
- [x] Gedit
- [x] Termius

Thanks!

**Comment by EliverLara** [comment]
Hi, I have added some of the requested icons, just missing "termius", Could you provide some image of the default icon  for that application? just to have an idea of ​​its design

**Comment by domenicoblanco** [comment]
Hi, thanks for your work!
This is the icon taken from their [website](https://termius.com/). 
![5c7036349b54772a93f82a6d_termius-logo](https://user-images.githubusercontent.com/9018104/59204306-a6254780-8ba0-11e9-90e7-d6efa8ecd03e.png)

This is the one taken from the Play Store
![ezgif-4-dcb494ddebf9](https://user-images.githubusercontent.com/9018104/59204431-e97fb600-8ba0-11e9-804c-e5cfe089d792.png)
