### ISSUE TITLE
Icons are present, but not shown in SysTray

### ISSUE THREAD

**Issue by FF-AntiK** [EliverLara/candy-icons#431]
Some of the `candy-icons` won't show up in the SysTray of my Panel:
![Screenshot_20221005_110255](https://user-images.githubusercontent.com/65959608/194024371-025c75c5-9e25-490f-b512-76d2395f8748.png)

**Comment by Hasshu** [comment]
Those tray icons are defined by the Plasma Style (a.k.a. desktop theme).

See also https://www.reddit.com/r/kde/comments/fkeyto/how_to_change_system_tray_icons_i_want_to_use_a/

**Comment by FF-AntiK** [comment]
Thank you very much for the reply!
Can you tell me what's the preferred Plasma Style to use with `candy-icons`?

**Comment by Hasshu** [comment]
> Thank you very much for the reply!

o7

> Can you tell me what's the preferred Plasma Style to use with `candy-icons`?

As far as I know, [Sweet KDE](/EliverLara/Sweet-kde) is supposed to be the matching theme. Though, personally, I don't use it because of a [certain issue](/EliverLara/Sweet-kde/issues/3).

See also https://www.opendesktop.org/u/eliverlara

**Comment by FF-AntiK** [comment]
Yeah, I'm on Arch and installed `sweet-theme-full-git` in order to have the full suit of themes. But I have to say, the System Tray is even worse now. A mixture of Sweet KDE, candy, breeze and vendor icons....

But since this issue doesn't belong here I'm closing this.
Thanks again @Hasshu !

**Comment by Hasshu** [comment]
> But I have to say, the System Tray is even worse now. A mixture of Sweet KDE, candy, breeze and vendor icons....

@FF-AntiK Don't forget to restart Plasma for the theme to be applied properly. But yeah... In spite of Plasma's apparent flexibility when it comes to theming, and the sheer amount of third-party themes available out there, I keep returning to Breeze Dark (only changing the color scheme to [QogirManjaroDark](/vinceliuice/Qogir-kde/blob/master/color-schemes/QogirManjaroDark.colors)). Maybe I should give Kvantum another try... But I digress.

> Thanks again @Hasshu !

Glad to be of help. )
