### ISSUE TITLE
Install from KHotNewStuff is installing the pale variant.

### ISSUE THREAD

**Issue by arnauddupuis** [EliverLara/candy-icons#437]
A recent update through Discover got me wondering why the icon set was so... well pale. 
It's because it seems like the version available on store.kde.org is the pale branch of that repository.

See: https://store.kde.org/p/1305251

It should probably be a user choice to switch to the pale version.

Thanks for everything!!! I love your theme and icons!

**Comment by RealDoigt** [comment]
I was wondering why the icons seem so flat and dead :-( The firefox logo especially seems like it's fading out of existence like some moribund old man awaiting death.

**Comment by EliverLara** [comment]
Thank you so much for reporting! I just uploaded the correct version

**Comment by Stellarthoughts** [comment]
Problem is fixed, thank you very much!

**Comment by RealDoigt** [comment]
awesome, thank you!

**Comment by arnauddupuis** [comment]
> Thank you so much for reporting! I just uploaded the correct version

Of course! You are more than welcome! Thank you sooooo much for your work!
