### ISSUE TITLE
[Icon request] all Weather icons

### ISSUE THREAD

**Issue by ghost** [EliverLara/candy-icons#441]
- **App Name:**
- **Icon Name:**
- **Description:**
- **Webpage (optional):**
- **Original Icon:**
    
Hi,

In order to use the Weather widget correctly in KDE, it would require icons for all weather conditions (showers, clear, snow, ...) like 
Breeze theme does (see picture)
![image](https://user-images.githubusercontent.com/55478909/204253001-48931c7a-4086-46d3-9372-b07afc9f9fc6.png)

**Comment by Diyou** [comment]
Removing /apps/scalable/weather.svg would make the theme fallback to the breeze icons which could be used as a temporary fix or renaming it to weather-widget.svg and deleting the link.

**Comment by Diyou** [comment]
Is there a reason for having /apps/scalable/weather.svg ? It prevents individual icons (listed above) to fallback and uses the default icon for each like: 
![image](https://github.com/EliverLara/candy-icons/assets/21966966/4ec19c0e-9b70-4681-b92f-5acde017c886)
Same data without weather.svg : 
![image](https://github.com/EliverLara/candy-icons/assets/21966966/696dcaf2-9aa5-4e6b-ab94-19a9d49bffc2)

**Comment by EliverLara** [comment]
@Diyou Thanks for pointing that out! I've fixed it
