### ISSUE TITLE
[Icon request]  Ferris icon for Rust (*.rs) files

### ISSUE THREAD

**Issue by AydroPunk** [EliverLara/candy-icons#459]
- **App Name:** Rust (*.rs) files
- **Icon Name:** (*.rs)
- **Description:** An icon dedicated to the Rust archive (I would love it if the official Ferris mascot was the cover). It would be great to add it to this list of this fantastic set.
- **Webpage (optional):** https://rustacean.net/
- **Original Icon:** 
    
![default_icon](https://user-images.githubusercontent.com/90808551/216858558-075e7f35-8a5e-41dd-8a13-4f66902a24d8.svg)
**Ferris**
![rustacean-orig-noshadow](https://user-images.githubusercontent.com/90808551/216858681-cf8d5f13-4b0b-463c-94d8-39d414e51a40.svg)

**Comment by fieryfurry** [comment]
@EliverLara Please create a symlink for `text-rust.svg` as the current one does not work in some applications.

**Comment by AydroPunk** [comment]
> @EliverLara Please create a symlink for `text-rust.svg` as the current one does not work in some applications.

You are right @fieryfurry, the symbolic link does not work either and therefore does not show me the .rs files, I would appreciate it if you correct it, thank you
