### ISSUE TITLE
[Icon Request] Jetbrains Toolbox

### ISSUE THREAD

**Issue by MarcJose** [EliverLara/candy-icons#49]
Including
- [ ] IntelliJ IDEA Community
- [ ] PyCharm Community
- [ ] DataGrip
- [ ] GoLand
- [ ] MPS
- [ ] RubyMine
- [ ] IntelliJ IDEA Community Educational
- [ ] PyCharm Edu
- [ ] IntelliJ IDEA Ultimate
- [ ] Android Studio
- [ ] PyCharm Professional
- [ ] WebStorm
- [ ] CLion
- [ ] PhpStorm
- [ ] Rider

**Comment by EliverLara** [comment]
Could you request your icons in one single issue please?

**Comment by MarcJose** [comment]
Of course, sorry. Thought this would make it easier to search :)
