### ISSUE TITLE
Icons aren't applied to kde flatpaks.

### ISSUE THREAD

**Issue by shellheim** [EliverLara/candy-icons#493]
### Sorry for the terribly executed issue in #489.  Here's a better report of what I found.

Icons don't get applied to flatpaks from kde. This not a problem with flatpaks in general on my system but only the flatpaks from kde.  

Here's a few pictures. (sorry for the poor quality)  

Arianna (an epub reader) and okular (a document viewer) from kde don't have their candy-icons applied but Libreoffice, which is a flatpak on my system, does.  

![Screenshot_20230712-1](https://github.com/EliverLara/candy-icons/assets/116480892/1894a05f-ceb1-433a-b16c-d2801455792e)  

Dolphin,kde's file manager, doesn't have it's icon applied but Fedora Media writer does.

![Screenshot_20230712](https://github.com/EliverLara/candy-icons/assets/116480892/c753f511-9b29-4ead-9bf6-5d69f63a6958)

This doesn't happen with GNOME's flatpaks, as can be seen with gnome-logs.  

![Screenshot_20230712-2](https://github.com/EliverLara/candy-icons/assets/116480892/3280cdbe-9678-4e6e-8def-ab9b85876808)  

### Workaround  and it's limits.
There's a workaround, simply edit the app's .desktop file and change the 'Icon' field's value from something like org.kde.okular to document-viewer and then either clear icon cache or change the icons temporarily to something else and then change back.

Example  

This doesn't work ❌
```desktop
[Desktop Entry]
Terminal=false
Name=Okular
Name[de]=Okular
Name[el]=Okular
Icon=org.kde.okular
```  

This does ✅
```desktop
[Desktop Entry]
Terminal=false
Name=Okular
Name[de]=Okular
Name[el]=Okular
Icon=document-viewer
```

However, this ceases to work when the flatpak is updated and it's .desktop file re-written.

## What I use 
OS : Fedora 38  
DE : KDE Plasma 5.27 
Kernel Version : `kernel-6.3.12-200.fc38.x86_64`

**Comment by Vilianexe** [comment]
it happen because the app as flatpak has a different name as the "official" app, i helped making a pull request with just a symlink to the original app-icon-name, pointing to the "new" name(that why the libre office has the icons, someone already patched it, but i guess anyone saw the kde icon) you can help too ;)

**Comment by shellheim** [comment]
I knew that, but could you tell what exactly I can do, thanks for responding.

**Comment by shellheim** [comment]
The maintainer doesn't seem to be paying attention to this project either.
