### ISSUE TITLE
Icons request

### ISSUE THREAD

**Issue by ana-clara** [EliverLara/candy-icons#5]
Hi, I like your icons very much, could you please add the following icons? (Sorry if the list is very long).

- [x] VSCodium (maybe the same icon from VSCode)
- [x] Steam
- [x] Lollypop
- [x] LibreOffice
- [x] VLC
- [x] Firefox Developer
- [x] Atom
- [x] Discord

Thanks! :)

**Comment by RlndVt** [comment]
To add to the list:

- [ ] Spotify
- [ ] Kate (/kwrite)
- [ ] Okular

**Comment by EliverLara** [comment]
Hi @stagyl, I have added some of the requested icons, just missing  "Lollypop", Could you provide some image of the default icon  for that  application? just to have an idea of ​​its design

**Comment by stagyl** [comment]
> Hi @stagyl, I have added some of the requested icons, just missing "Lollypop", Could you provide some image of the default icon for that application? just to have an idea of ​​its design

![image](https://user-images.githubusercontent.com/38473924/59970550-6d418700-953f-11e9-8b2e-54aeac97dd66.png)
