### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by EliverLara** [EliverLara/candy-icons#52]
- [x] - Foliate
- [x] - Frans
- [x] - Gnome Disks
- [x] - Gufw
- [x] - HPLIP Toolbox
- [ ] - IcedTea Web Control Panel
- [x] - KchmViewer
- [x] - kinfocenter
- [x] - Kleopatra
- [x] - LibreOffice Startcenter
- [x] - Netbeans
- [x] - phpMyAdmin
- [x] - qBitorrent
- [ ] - R (language programming)
- [ ] - Robocode
- [x] - RStudio
- [ ] - SpeedCrunch
- [x] - Visual Studio Code
- [x] - VokoScreen
- [ ] - XSane
- [x] - Yakuake
- [x] - And the categories in the KDE System Settings

**Comment by bursterburster** [comment]
- [ ] PuTTY

**Comment by encrustace** [comment]
- [ ] Intellij Idea Community Edition
- [ ] Gnome Characters
- [ ] Gnome Clock
- [ ] Gnome Archive Manager
- [ ] Gnome Boxes
- [ ] Gnome Fonts
- [ ] Vim

**Comment by ZachBaird** [comment]
Hello Eliver! Running Gnome on my machine, but can't get the Visual Studio Code icon to work. Any ideas? I confirmed that it's in the folder I downloaded from pling.com.

**Comment by ZachBaird** [comment]
Forget my earlier comment. There's about 3 ways to download vscode: either through the software store, through snap, or through the .deb. If you download through either snap or the software store, the code.desktop doesn't get generated as far as I can find. As a matter of fact, I couldn't find where vscode got installed at all in those 2 circumstances.

Installing the .deb from https://code.visualstudio.com/ allowed me to find the code.desktop in /usr/share/applications and edit what icon it looks for.

**Comment by denikris** [comment]
- [ ] About Xfce (xfce4-about.desktop)
- [ ] Window Manager (xfce-wm-settings.desktop)
- [ ] Notifications (xfce4-notifyd-config.desktop)
- [ ] Application Finder (xfce4-appfinder.desktop)
