### ISSUE TITLE
Kdenlive icon overrides (too) many of the application's icons

### ISSUE THREAD

**Issue by Nightfirecat** [EliverLara/candy-icons#520]
- **App Name:** Kdenlive
- **Icon Name:** kdenlive.svg
- **Description:**

The icon provided in this pack works well for the application, however I'm seeing that it applies in many more places than just the application bar icon--for instance, the top-left looks like this: (where the buttons appear to be, in order: all, video, audio, templates, favorites, download)
![](https://github.com/EliverLara/candy-icons/assets/2199511/53bcc8e5-9517-42ed-a2de-d37678cfbfc9)

and the bottom-right looks like this: (these buttons are, in order: Show Color Tags in timeline, Show Video Thumbnails, Show Audio Thumbnails, Show Markers Comments, Snap)
![](https://github.com/EliverLara/candy-icons/assets/2199511/0614bae8-1e4e-4f34-b40b-11429122e94f)

I'm not sure how this icon override works, but I'm fairly certain the original icons aren't the same as the original Kdenlive icon.

**Comment by Vilianexe** [comment]
you can disable that on kdenlive, on the top bar you can "force breeze icon" and it fixed for me, i also don't understand with it override that many icons

**Comment by Nightfirecat** [comment]
That works perfectly! Thanks.
