### ISSUE TITLE
[Icon request] Thorium Browser

### ISSUE THREAD

**Issue by max2000warlord** [EliverLara/candy-icons#527]
**App Name:** Thorium Browser
**Icon Name:** thorium-browser
**Description:** Chromium fork focused on high performance and security
**Webpage (optional):** https://thorium.rocks/
**Original Icon:**
    
![thorium](https://github.com/EliverLara/candy-icons/assets/13299086/d89072a7-0812-4d1b-8ab9-9039bc0a41c7)

**Comment by Alex313031** [comment]
@max2000warlord @EliverLara The original source for the svg of the icon is > https://github.com/Alex313031/thorium/blob/main/logos/NEW/thorium.svg
