### ISSUE TITLE
[Icon request] Mercury Browser

### ISSUE THREAD

**Issue by max2000warlord** [EliverLara/candy-icons#528]
- **App Name:** Mercury Browser
- **Icon Name:** mercury
- **Description:** Compiler optimized, private Firefox fork
- **Webpage (optional):** https://thorium.rocks/mercury
- **Original Icon:**
    
           https://thorium.rocks/imgs/Mercury_2048.png

**Comment by Alex313031** [comment]
@max2000warlord @EliverLara The original .svg source for the logo is > https://github.com/Alex313031/Mercury/blob/main/logos/Mercury.svg
