### ISSUE TITLE
Mp3 icon missing

### ISSUE THREAD

**Issue by gitinho** [EliverLara/candy-icons#53]
I've been using candy icons for a while and today I noticed the mp3 icon disappeared. I'm pretty sure it was there before. This may have happened after I updated plasma to 5.17.0

**Comment by EliverLara** [comment]
Thanks for reporting! Is this issue still happening?

**Comment by gitinho** [comment]
Not anymore, I'm afraid I won't be able to provide more details. I might have fixed it by manually changing the icon for the filetype, I don't remember for sure. It was more than two weeks ago. Or maybe a restart solved the problem. Unless you did something. Anyway, thanks for your work. I love the look of candy icons + sweet theme.

**Comment by EliverLara** [comment]
Thanks! I'm glad you were able to fix the issue.
