### ISSUE TITLE
Request icons

### ISSUE THREAD

**Issue by Paullux** [EliverLara/candy-icons#55]
Hello,

Can you create icons for :

- [x] - makehuman
- [x] - gnome-mines
- [x] - blender
- [x] - godot
- [x] - wire
- [x] - Lightbeats
- [x] - Qt Creator
- [ ] - Molotov
- [x] - clementine
- [x] - pamac
- [ ] - firestorm

thanks

**Comment by encrustace** [comment]
Blender is done

**Comment by EliverLara** [comment]
I have already added some of the icons, Could you provide some example(maybe default icon) of the remaining icons?
