### ISSUE TITLE
Prism Launcher

### ISSUE THREAD

**Issue by AceSardonyx** [EliverLara/candy-icons#572]
https://prismlauncher.org
Best minecraft launcher everrrr. Have you heard?!

I donated on paypal btw, tysm for creating stuff :)
I love linux

**Comment by Red6785** [comment]
- **App Name: Prism Launcher**
- **Icon Name: org.prismlauncher.PrismLauncher**
- **Description: A custom launcher for Minecraft that allows you to easily manage multiple installations of Minecraft at once.**
- **Webpage: https://prismlauncher.org/**
- **Original Icon:**
![org prismlauncher PrismLauncher Source](https://github.com/EliverLara/candy-icons/assets/88458171/5a0d9f87-5647-42cb-9ddd-80e055b68f71)

**Comment by EliverLara** [comment]
@AceSardonyx I've added the icon, thank you so much for your donation and support! :)
