### ISSUE TITLE
Some app icons aren't being replaced (Ubuntu 19.10)

### ISSUE THREAD

**Issue by Joao-PauloTI** [EliverLara/candy-icons#58]
Hi there. Some app icons such as LibreOffice and Visual Studio Code aren't being replaced by their Candy versions, at least on my system.
Is there something I can do to fix it? The Candy-icons folder are located in /Home/Me/.icons and I set it up with Gnome Tweaks, by the way.

![Captura de tela de 2019-11-09 14-33-20](https://user-images.githubusercontent.com/44660633/68532684-66a18980-02ff-11ea-94b0-a68cde7e2407.png)
![Captura de tela de 2019-11-09 14-44-03](https://user-images.githubusercontent.com/44660633/68532729-bf712200-02ff-11ea-8a46-2fd0a3e1c7d2.png)

**Comment by encrustace** [comment]
Maybe you've not installed the latest version of LibreOffice, Ubuntu is not rolling release so it may possible, Can you send App version you've installed which missing icons?

**Comment by Joao-PauloTI** [comment]
> Maybe you've not installed the latest version of LibreOffice, Ubuntu is not rolling release so it may possible, Can you send App version you've installed which missing icons?

libreoffice 6.3.3.2 (installed via snap)
code (Visual Studio Code) 1.40.0 (installed via .deb)
mailspring 1.7.2 (installed via .deb) - I'm not sure if there's a Candy version for this app's icon

**Comment by EliverLara** [comment]
Sadly snap packages have hardcoded paths to icons that's why libreoffice icons don't change, Could you provide the  **Icon Name:** entry for vscode please? you can fint this entry in the app's desktop-file, usually placed in /usr/share/applications/ folder (Ex. /usr/share/applications/firefox.desktop).

**Comment by Joao-PauloTI** [comment]
Yeah, I reinstalled libreoffice via apt and now it's icons are replaceable.
About vscode, the icon entry is `Icon=/usr/share/pixmaps/com.visualstudio.code.png` .
Had to change to `Icon=visual-studio-code` to make it work with any icon theme.

**Comment by EliverLara** [comment]
@Joao-PauloTI thanks for the info!  apparently vscode also had a hardcoded path to icon.
