### ISSUE TITLE
[Icon request] Zed

### ISSUE THREAD

**Issue by arunoruto** [EliverLara/candy-icons#600]
- **App Name:** Zed
- **Icon Name:** zed
- **Description:** A high-performance, multiplayer code editor.
- **Webpage (optional):** [https://zed.dev/](https://zed.dev/)
- **Original Icon:** 
![zed-icon](https://github.com/user-attachments/assets/bcd88ba9-487a-4c63-aeb3-ac2cda2702d3)

**Comment by arunoruto** [comment]
An icon got added! Thanks a lot for the quick feedback :D

**Comment by felipetesc** [comment]
Thanks!
