### ISSUE TITLE
[Icon request] Zen Browser

### ISSUE THREAD

**Issue by arunoruto** [EliverLara/candy-icons#603]
- **App Name:** Zen
- **Icon Name:** zen
- **Description:** A privacy oriented browser based on firefox with utilities from arc.
- **Webpage (optional):** https://zen-browser.app/
- **Original Icon:**
![zen-black](https://github.com/user-attachments/assets/3986ef5a-259b-481d-9d27-18be1a3100b9)

**Comment by TLCPlusPlus** [comment]
Please add a copy of "zen.svg" for "io.github.zen_browser.zen.svg" for flatpak installs.

**Comment by TLCPlusPlus** [comment]
under "breaking changes" Zen changed its Flatpak ID.

" Changed flatpak id from 'io.github.zen_browser.zen' to 'app.zen_browser.zen' "

https://zen-browser.app/release-notes/#1.7b
