### ISSUE TITLE
[Icon request] Development tools

### ISSUE THREAD

**Issue by suve** [EliverLara/candy-icons#61]
It would be great if the set contained more icons for FOSS software / electronics development tools.

- [x] Anjuta
- [x] Arduino IDE
- [x] CAMotics
- [x] CMake GUI
- [x] Code::Blocks IDE
- [x] Eclipse IDE
- [x] FreeCAD
- [x] Fritzing
- [x] Geany
- [x] GHex (GNOME Hex Editor)
- [x] Ghostwriter
- [x] GNU Octave
- [x] KiCad
- [x] Lazarus
- [x] Logisim
- [x] MonoDevelop
- [x] MySQL Workbench
- [x] Poedit
- [x] Scratch (programming language)
- [x] Spyder
- [x] Umbrello

Sorry for just throwing those over the wall. I really wish I could contribute icons.

**Comment by EliverLara** [comment]
Hi, I have already added some of the icons, Could you provide some example(maybe default icon image) of the remaining icons?

**Comment by suve** [comment]
Big thanks! Here are the icons/logos for the remaining programs:

-----

**Camotics**: ![link](https://raw.githubusercontent.com/CauldronDevelopmentLLC/CAMotics/master/images/camotics.png)

-----

**KiCad**: ![link](https://git.launchpad.net/kicad/plain/bitmaps_png/icons/icon_kicad_64.png)

-----

**Lazarus**: ![link](https://www.lazarus-ide.org/favicon.ico)

-----

**MonoDevelop**: ![link](https://www.monodevelop.com/images/md-logo.svg)

-----

**Poedit**: ![link](https://d33wubrfki0l68.cloudfront.net/eb5ace28e7d05fb5ba0090147922de976fe48f9f/5967e/images/icons/poedit/icon_128x128@2x.png)

-----

**Scratch**: ![logo](https://scratch.mit.edu/images/logo_sm.png)

Alternatively, the Scratch mascot is second-right in this image: ![mascot](https://cdn.scratch.mit.edu/scratchr2/static/images/help/spritesforcommunityguid.png)

-----

**Spyder**: ![logo](https://www.spyder-ide.org/static/images/spyder-logo.svg)

-----

**Umbrello**: ![logo](https://dashboard.snapcraft.io/site_media/appmedia/2019/01/umbrello.svg.png)

**Comment by WhiteBahamut** [comment]
would be great to also have a VS Code Icon
![vs code](https://upload.wikimedia.org/wikipedia/commons/9/9a/Visual_Studio_Code_1.35_icon.svg)

**Comment by EliverLara** [comment]
@WhiteBahamut The icon for vscode already exists in this pack.

**Comment by WhiteBahamut** [comment]
when it was added? I still have the default VS Code icon :(

**Comment by EliverLara** [comment]
@WhiteBahamut It was added since the first release, take a look at  #76 maybe that solves your problem.

**Comment by WhiteBahamut** [comment]
Thanks! added my 50cent to #76. Works now! :)

**Comment by suve** [comment]
Just wanted to say: thanks for all your work. The icons are great, just like the rest of the theme.
