### ISSUE TITLE
[Icon request] Slack

### ISSUE THREAD

**Issue by screwb0x** [EliverLara/candy-icons#617]
- **App Name: Slack Chat**
- **Icon Name: Slack**
- **Description: Slack is Business tool for group-chats like MS-Teams etc.**
- **Webpage (optional): https://slack.com**
- **Original Icon:**
![slack](https://github.com/user-attachments/assets/17187852-e68a-48e2-8349-d395d70ad6d7)

**Comment by EliverLara** [comment]
There is already an [icon for slack](https://github.com/EliverLara/candy-icons/blob/master/apps/scalable/slack.svg) in this pack
