### ISSUE TITLE
[Icon Request]

### ISSUE THREAD

**Issue by drunkpegasus** [EliverLara/candy-icons#63]
Can you add an icon for Discord? Love your work!

**Comment by EliverLara** [comment]
Hi, there is actually an icon for discord

**Comment by drunkpegasus** [comment]
![Screenshot from 2019-11-26 13-13-27](https://user-images.githubusercontent.com/48221662/69609031-a7fb9e00-104e-11ea-9adb-eab368df1c42.png)
it's not showing up for me for some reason then. Any idea what must be wrong? (I used snap to install it)

**Comment by EliverLara** [comment]
Sadly, snap applications have hardcoded links to icons,you could try installing it using a `.deb` file

**Comment by drunkpegasus** [comment]
installing it by the .deb file worked. thanks!
