### ISSUE TITLE
Is it possible to get an android icon pack?

### ISSUE THREAD

**Issue by epsilon-0** [EliverLara/candy-icons#66]
This is really really amazing!!

I was wondering if it is possible to get this on android?

**Comment by EliverLara** [comment]
Hi, I'm not sure about that, I haven't created an Android icon theme so far.

**Comment by epsilon-0** [comment]
There seems to be a similar closed source app: LineBit icons (https://play.google.com/store/apps/details?id=com.edzondm.linebit&hl=en_US)

I wasn't sure if this is the same but they look very similar. 
I just wanted to make sure no one is going around stealing stuff!

**Comment by EliverLara** [comment]
Thank you, I already knew about linebit icons, but they are a different project.
