### ISSUE TITLE
[Icon request] MATLAB

### ISSUE THREAD

**Issue by abraha2d** [EliverLara/candy-icons#67]
Great icon theme, well done! Noticed a few icons missing:

* [x]  [MATLAB](https://packages.ubuntu.com/bionic/matlab-support)
* [x]  GIMP, Flatpak version (added in my PR)
* [x]  Ukuu (added in my PR)

Also the Jetbrains IDEs, but those have been mentioned in previous issues.

See PR at #68.

**Comment by lambtho12** [comment]
This logo seems to fit quite well the theme, I think a slight change in the color gradient might be appropriate though.
https://seeklogo.com/vector-logo/333704/matlab

**Comment by abraha2d** [comment]
The color gradient looks fine, not out of place. Agreed with making the lines thicker and removing the interior shading, to match other icons.

**Comment by EliverLara** [comment]
I have two options for the matlab icon (including the one @lambtho12  proposed):

**Option1**

![Captura de pantalla de 2019-12-13 13-01-43](https://user-images.githubusercontent.com/9838260/70825864-10ff4780-1dab-11ea-8b28-4b0a00cf78fe.png)

**Option 2**

![Captura de pantalla de 2019-12-13 13-04-46](https://user-images.githubusercontent.com/9838260/70825873-19f01900-1dab-11ea-9807-881bd2b83c30.png)


Which option looks best for you?

**Comment by abraha2d** [comment]
I'm leaning towards Option 1, as i think it fits better. Maybe something like this will fit even better, what do you think?
![Screenshot_20191213_144013](https://user-images.githubusercontent.com/5976139/70827120-92100c00-1db6-11ea-89bb-bb165e56fe91.png)

**Comment by lambtho12** [comment]
I prefer option 1 as well in general and the one propose by @abraha2d seems to be more straight to the point. I really like it.

**Comment by EliverLara** [comment]
Done.
