### ISSUE TITLE
VSCode icon is not being used

### ISSUE THREAD

**Issue by coyotefoxtrot** [EliverLara/candy-icons#76]
For VSCode the Candy icon isn't being utilized, it's just the plain jane blue icon...I originall had vscode installed as a snap, so I thought that was the issue...but then removed it and installed it normally via apt and the issue remains.

![Screenshot from 2019-12-28 07-22-01](https://user-images.githubusercontent.com/56912051/71545657-ccdf7b80-2942-11ea-963e-98b7dc84c3b3.png)

**Comment by coyotefoxtrot** [comment]
edited the two lines for `Icon` in /usr/share/applications/code.desktop by changing them to `/usr/share/icons/candy-icons/apps/scalable/code.svg`

**Comment by EliverLara** [comment]
The easiest way would be to change that line for this: `Icon=code` or  `Icon=com.visualstudio.code`, so that would make the icon adapt to the icon theme you are using.

**Comment by coyotefoxtrot** [comment]
Thank you for the tip, I updated it to simply `code`

**Comment by WhiteBahamut** [comment]
for me it was in `/home/NAME/.local/share/applications/`
