### ISSUE TITLE
[Icon request] Kodi Icon, nvidia-settings icon

### ISSUE THREAD

**Issue by AToMiXhawK** [EliverLara/candy-icons#77]
![kodi](https://user-images.githubusercontent.com/42279685/71583551-fa8c1680-2b34-11ea-865c-7eb28f9a5b86.png)
![nvidia](https://user-images.githubusercontent.com/42279685/71583552-fa8c1680-2b34-11ea-914c-9bdbc25b2797.png)
Please consider adding these icons, many users use kodi and have and nvidia driver.
Attached the icons I custom made to use with candy icons

**Comment by EliverLara** [comment]
Hi, you icons looks great, would you consider contributing by adding them to this repo?

**Comment by AToMiXhawK** [comment]
> Hi, you icons looks great, would you consider contributing by adding them to this repo?
These are png icons. Should i make svg ones for contributing?

**Comment by AToMiXhawK** [comment]
> Hi, you icons looks great, would you consider contributing by adding them to this repo?

These are png icons. Should I make svg ones for contributing?

**Comment by EliverLara** [comment]
Added in the last update!
