### ISSUE TITLE
[Icon Request] Visual Studio Code and Musescore 3

### ISSUE THREAD

**Issue by smhsketch** [EliverLara/candy-icons#78]
Could you consider adding an icon for VSCode and MuseScore 3? I love your icon pack, but two of the programs I use most often do not have icons. Could you possibly make icons for these two programs?

![image](https://user-images.githubusercontent.com/38465129/71768037-a7bdb080-2ee0-11ea-8a3f-545b430e6c0f.png)

![image](https://user-images.githubusercontent.com/38465129/71768035-a2606600-2ee0-11ea-966a-353551b7286c.png)

**Comment by tobias-tengler** [comment]
[Visual Studio Code](https://github.com/EliverLara/candy-icons/blob/master/apps/scalable/code.svg) already has a matching icon. Please make sure you have the latest version of the icon package installed and searched the repository for an icon, before submitting a request.

**Comment by EliverLara** [comment]
@tobias-tengler Thanks for the help! you're right vscode already has a matching icon and i've added musescore icon in the last commits.
