### ISSUE TITLE
[Icon Request] Jetbrains Webstorm, Jetbrains Datagrip, Spotify, Postman, Stoplight Studio

### ISSUE THREAD

**Issue by Kent55** [EliverLara/candy-icons#79]
Lovely icon set! Just a few icons that are missing that would complete my toolbar set :)

- [x] [Jetbrains Webstorm](https://www.jetbrains.com/webstorm)
- [x] [Jetbrains Datagrip](https://www.jetbrains.com/datagrip)
- [x] [Spotify](https://www.spotify.com)
- [x] [Stoplight Studio](https://stoplight.io/studio/)

Some extras which would be welcomed too:

- [x] [Android Studio](https://developer.android.com/studio)
- [x] [Burp suite community edition](https://portswigger.net/burp/communitydownload)
- [x] Calculator (Built in to OS - currently running Ubuntu 19.10)
- [x] [AppImage Launcher](https://www.linux-apps.com/p/1228228/)
- [x] [WPS Office set](https://www.wps.com/)
- [x] [Hyper](https://hyper.is/) 

![candy-icons-dock](https://user-images.githubusercontent.com/5375354/71768512-765bd980-2f0e-11ea-976e-5c4e27204791.png)

Awesome work again, much appreciated :)

**Comment by tobias-tengler** [comment]
[Spotify](https://github.com/EliverLara/candy-icons/blob/master/apps/scalable/spotify-client.svg), [Android Studio](https://github.com/EliverLara/candy-icons/blob/master/apps/scalable/androidstudio.svg) and [Calculator](https://github.com/EliverLara/candy-icons/blob/master/apps/scalable/accessories-calculator.svg) are already present. Are you sure you have the latest version of the icon package?

**Comment by Kent55** [comment]
Hi @tobias-tengler thanks for your reply. I have just manually reinstalled the icons, downloading the latest `.tar.xz` from https://www.opendesktop.org/p/1305251/ and have verified that it shows icons for Spotify, Android Studio, Calculator and Postman within the download. However, they all seem to still not be taking effect (all the others seem to work). 

I've extracted the tarball and placed it inside `/usr/share/icons/candy-icons` setting file permissions recursively to 755 for the directory.

Is there anything you can think of as to why it could be that for me, all other icons are being updated, but not for the apps listed above? I have uninstalled and reinstalled Spotify and restarted my PC to see if that worked, but unfortunately still to no avail.

**Comment by Kent55** [comment]
Hi @tobias-tengler thanks for your reply. I have verified that all the icons for the aforementioned applications do exist within my `candy-icons` directory. I did reinstall the icons manually again anyway.

After doing some digging it seems to be because each of the applications (with the exclusion of Postman which I seemed to have installed manually) are installed as snaps (_Spotify, Android Studio, Calculator_).

For more info this is discussed in this post: https://forum.snapcraft.io/t/use-the-system-gtk-theme/496/3

![snap-calculator](https://user-images.githubusercontent.com/5375354/71842232-1190b280-30b9-11ea-91bf-ac3fa1fa007d.png)
![snap-spotify](https://user-images.githubusercontent.com/5375354/71842234-12294900-30b9-11ea-8f26-0dda21de59ed.png)
![snap-android-studio](https://user-images.githubusercontent.com/5375354/71842235-12294900-30b9-11ea-9799-38b8926f0da2.png)

I'm currently running Ubuntu `19.10` but upgraded from Ubuntu `18.04`, which from finding [this question posted on ask ubuntu](https://askubuntu.com/questions/1050235/missing-calculator-icon-in-ubuntu-18-04-with-vanilla-gnome), it states that the calculator by default is also a snap application in Ubuntu `18.04`.

As a workaround either creating a custom `.desktop` launcher or finding a native version of the application fixes the issue.
