### ISSUE TITLE
KDevelop5 Icon

### ISSUE THREAD

**Issue by Raincode** [EliverLara/candy-icons#80]
Hi!

Amazing icon pack!

I noticed KDevelop IDE doesn't seem to have an icon. The official one can be found [here (.svg)](https://upload.wikimedia.org/wikipedia/commons/c/cf/Breezeicons-apps-48-kdevelop.svg).

I tried to make one myself, but honsetly it's not really 100%. I'm not experienced with vector graphics.

Any ideas how to improve it? I didn't get the gears in the style of other existing icons. The center one is the original.

![kdevelop_icons](https://user-images.githubusercontent.com/3680725/71824703-7c7ec100-309a-11ea-9086-0123f8c3e2b6.png)

**Edit:**
I think out of those four, the top or bottom ones are better...

**Comment by EliverLara** [comment]
Hi, I think the one on the top looks great, Would you consider contributing by adding that icon?

**Comment by Raincode** [comment]
Nice, thank you, I think I agree.

Sure... I did something really stupid; I reinstalled my OS and wiped my home drive in the process (which had the .svg), but I will try to recreate it m(  ... Might take a couple days until I find some time.

**Comment by EliverLara** [comment]
Added in the last update!
