### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by ghost** [EliverLara/candy-icons#82]
- [x] dia
- [x] gradio
- [x] drawing
- [x] gnome-contacts
- [x] meld
- [x] gnome-sound-recorder
- [x] baobab
- [x] pulseaudio
- [x] firewall-config
- [x] dconf-editor
- [x] gnome-abrt
- [x] gnome-font-viewer
- [x] gnome-usage

Regards!

**Comment by demon-sword** [comment]
stremio

**Comment by EliverLara** [comment]
Done!
