### ISSUE TITLE
[Icon Request] Minecraft Launcher

### ISSUE THREAD

**Issue by smhsketch** [EliverLara/candy-icons#83]
Search the repository and found nothing for Minecraft. I'd appreciate if you added one. :)

![image](https://user-images.githubusercontent.com/38465129/72480309-0dede180-37c5-11ea-9138-793b79713232.png)

**Comment by Kasonnara** [comment]
Tried to make some icons to extend this beautiful theme. Here what I manage to achieve for the minecraft logo. 

Guys, tell me if one seems ok for you and I would make a PR for it.

1. ![minecraft-S](https://user-images.githubusercontent.com/32736398/87964994-59a67e00-cabb-11ea-9d1f-f59d3c45fcbc.png)
1. ![minecraft-S-yellow](https://user-images.githubusercontent.com/32736398/87964995-5a3f1480-cabb-11ea-9ed2-fc7c655be32d.png)
1. ![minecraft-face-yellow-contrast](https://user-images.githubusercontent.com/32736398/87964989-590de780-cabb-11ea-97ef-cb9ca83f5fc1.png)
1. ![minecraft-top_face-contrast](https://user-images.githubusercontent.com/32736398/87965000-5ad7ab00-cabb-11ea-99e5-2c39c3b7725c.png)
1. ![minecraft-full_top_face-contrast](https://user-images.githubusercontent.com/32736398/87964993-59a67e00-cabb-11ea-99fe-c15fda35acb9.png)

**Comment by EliverLara** [comment]
Hi @Kasonnara, your icons looks great!, I think the third option look more suitable for this icon theme, if you could use the third icon with the colors of the second one it would be great.

**Comment by smhsketch** [comment]
Personally I like #1 because of the colors matching more closely and the simpler, one-line design, but these are all fantastic!

**Comment by Kasonnara** [comment]
Something like that? 
![minecraft-face-yellow-distinct](https://user-images.githubusercontent.com/32736398/91839469-63410b00-ec4f-11ea-9765-5616e909c8dd.png)

*(Sorry for the delay I missed the notification)*

**Comment by Paragoumba** [comment]
Hi, I tried to do an icon for the Minecraft Launcher before seeing this issue. Here it is:
![image](https://user-images.githubusercontent.com/22895992/93723575-f1017d80-fb9f-11ea-81c5-f13fc2bace03.png)
It isn't finished yet but maybe @Kasonnara's icons are better.
I'm about to do a big pull request with lots of other icons and I'd like to add the Minecraft Icon. Which one should I use?
