### ISSUE TITLE
[Icon Request] Electronic-wechat, Charles

### ISSUE THREAD

**Issue by sanwanliu** [EliverLara/candy-icons#86]
Could you add the following icons, thanks

- [x]  electronic-wechat

- [x]  charles

**Comment by sanwanliu** [comment]
![image](https://user-images.githubusercontent.com/23079982/73518237-b85a3b80-4438-11ea-8594-c91eeea8bf7a.png)

![image](https://user-images.githubusercontent.com/23079982/73518270-c8721b00-4438-11ea-9811-4ee3c4e99132.png)

**Comment by EliverLara** [comment]
Added!
