### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by theAndrewCline** [EliverLara/candy-icons#87]
It would be awesome if you could use the terminal icon for the Alacrity app. 

Also, would be cool to have an icon for Pop! Shop. (app manager for Pop!_os)

**Comment by nina-j** [comment]
+1 for Alacritty, currently looks like this in my KDE environment:
![image](https://user-images.githubusercontent.com/28903001/74023708-94e74180-49a0-11ea-8de0-bc0e71c85edb.png)

**Comment by olealgoritme** [comment]
Definitely wanting Alacritty icon. :-))

**Comment by Lucretia** [comment]
There's quite a few missing from KDE, especially the icons in the system tray, notifications and system settings.

Also, no

[] dropbox folder icon
[] Cadence
[] Carla, Catia, Claudia
[] Calf
[] OBS

**Comment by EliverLara** [comment]
`Alacritty` icon has just been added, @theAndrewCline Could you provide the `icon name` entry for the `Pop! Shop` app, please? (you can find it in the application's `.desktop` file)

**Comment by theAndrewCline** [comment]
com.alacritty.Alacritty

**Comment by theAndrewCline** [comment]
sorry reread what you said. 

the Pop!-shop icon name is pop-shop

**Comment by EliverLara** [comment]
Done!
