### ISSUE TITLE
[Icon Request] Alacritty, GoldenDict, Scribus, uGet

### ISSUE THREAD

**Issue by duongdominhchau** [EliverLara/candy-icons#90]
I find out that this great icon theme does not have icons for these applications below.
- [x] Alacritty
Icon name: Alacritty (https://github.com/alacritty/alacritty/blob/master/extra/linux/alacritty.desktop)
Original icon: https://github.com/alacritty/alacritty/blob/master/extra/logo/alacritty-term.svg
![image](https://user-images.githubusercontent.com/56427890/74800628-a4eb1380-5306-11ea-9759-d49f333404cf.png)
- [x] GoldenDict
Icon name: goldendict (https://github.com/goldendict/goldendict/blob/master/redist/goldendict.desktop)
Original icon: https://github.com/goldendict/goldendict/blob/master/redist/icons/goldendict.png
![image](https://user-images.githubusercontent.com/56427890/74800700-dfed4700-5306-11ea-992e-d871c83b0b4d.png)
- [x] Scribus
Icon name: scribus (https://github.com/scribusproject/scribus/blob/master/scribus.desktop.in, this one look more complex, but on Arch both the desktop file and icon file are named just `scribus`, no "tag version" followed)
Original icon: https://github.com/scribusproject/scribus/blob/master/resources/iconsets/artwork/icon_256x256.png
![image](https://user-images.githubusercontent.com/56427890/74801208-8259fa00-5308-11ea-9605-d5205b609108.png)
- [x] uGet
Icon name: uget-icon (https://sourceforge.net/p/urlget/uget2/ci/master/tree/uget-gtk.desktop)
Original icon: https://sourceforge.net/p/urlget/uget2/ci/master/tree/pixmaps/icons/hicolor/scalable/apps/uget-icon.svg
![image](https://user-images.githubusercontent.com/56427890/74800808-407c8400-5307-11ea-8c13-6beeb817863f.png)

**Comment by EliverLara** [comment]
Done!
