### ISSUE TITLE
Does this icon theme have icons for mimetypes?

### ISSUE THREAD

**Issue by duongdominhchau** [EliverLara/candy-icons#91]
I have just read the **Icon Naming Specification** from [freedesktop.org](https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html) and noticed that this icon theme does not have a `mimetypes` directory. Does this theme have icons for file types (e.g: ogg, mp3, flac, ...)?

By the way, thank you for creating this awesome icon theme, it is so beautiful and more complete than most of other icon theme I have tried. Thank you!

**Comment by EliverLara** [comment]
Hi, for now the development is focused on application icons, anyway, you can easily edit the `index.theme` file to inherit those files from another icon theme.

**Comment by duongdominhchau** [comment]
Thank you.
