### ISSUE TITLE
[Icon request] WPS Office

### ISSUE THREAD

**Issue by sanwanliu** [EliverLara/candy-icons#96]
I hope to add the following icons, thank you

- [x] wps-office-prometheus

- [x] wps-office-pdf

- [x] wps-office-wpp

- [x] wps-office-et

- [x] wps-office-wps

https://www.wps.com/

![image](https://user-images.githubusercontent.com/23079982/75350869-2b44be00-58e2-11ea-9dba-e5b3f3a92943.png)

**Comment by EliverLara** [comment]
Hi, there are already icons for` wps-writer`, `wps-presentation `and `wps-spreadsheets`, Could you provide the icon name entry for the remaining apps, please? (you can find it in the application's .desktop file)

**Comment by sanwanliu** [comment]
is this?
![image](https://user-images.githubusercontent.com/23079982/76331277-debda180-6329-11ea-840f-28819412405d.png)

**Comment by EliverLara** [comment]
Yes, open those files and search for the `icon` entry.

**Comment by sanwanliu** [comment]
![image](https://user-images.githubusercontent.com/23079982/76371895-bc05aa00-6376-11ea-8c4f-3f3b3488c765.png)
![image](https://user-images.githubusercontent.com/23079982/76371922-d63f8800-6376-11ea-93b7-889d2279f709.png)
![image](https://user-images.githubusercontent.com/23079982/76371943-e3f50d80-6376-11ea-8b66-88e1c33db415.png)
![image](https://user-images.githubusercontent.com/23079982/76371959-f2dbc000-6376-11ea-9d8f-aa5c3c22ea97.png)
![image](https://user-images.githubusercontent.com/23079982/76371983-02f39f80-6377-11ea-9f37-0868f5325e93.png)

**Comment by EliverLara** [comment]
Done!
